CREATE TABLE [dbo].[Agency] (
    [AgencyNbr]            CHAR (3)         NOT NULL,
    [CountyNbr]            CHAR (3)         NOT NULL,
    [BranchNbr]            CHAR (3)         NOT NULL,
    [SalesDistrictNbr]     CHAR (2)         NOT NULL,
    [AgencyNm]             CHAR (35)        NULL,
    [SalesRegionCd]        CHAR (2)         NULL,
    [AgencyUPSZoneCd]      CHAR (2)         NULL,
    [AgencyManagerNbr]     CHAR (4)         NULL,
    [AddressLine1Desc]     VARCHAR (100)    NULL,
    [AddressLine2Desc]     VARCHAR (100)    NULL,
    [StreetAddressDesc]    VARCHAR (100)    NULL,
    [CityNm]               CHAR (30)        NULL,
    [ZipCd]                CHAR (9)         NULL,
    [StateOrProvinceCd]    CHAR (3)         NULL,
    [AgencyLatitudeNbr]    DECIMAL (13, 10) NULL,
    [AgencyLongitudeNbr]   DECIMAL (13, 10) NULL,
    [AgencyGeoAddressDesc] VARCHAR (200)    NULL,
    [PhoneAreaCodeNbr]     CHAR (3)         NULL,
    [PhoneExchangeNbr]     CHAR (3)         NULL,
    [PhoneLocalNbr]        CHAR (4)         NULL,
    [PhoneNbr]             CHAR (16)        NULL,
    [AccountBillInd]       CHAR (1)         NULL,
    [EFTMembershipInd]     CHAR (1)         NULL,
    [AOACashReceiptCd]     CHAR (1)         NULL,
    [AOANewBusinessCd]     CHAR (1)         NULL,
    [UpdatedTmstmp]        DATETIME2 (7)    NOT NULL,
    [UserUpdatedId]        CHAR (8)         NOT NULL,
    [LastActionCd]         CHAR (1)         NOT NULL,
    [SourceSystemCd]       CHAR (2)         NOT NULL,
    CONSTRAINT [PK_Agency] PRIMARY KEY CLUSTERED ([AgencyNbr] ASC, [CountyNbr] ASC, [BranchNbr] ASC) ON [AGENCYCD],
    CONSTRAINT [FK_Agency_County_01] FOREIGN KEY ([CountyNbr]) REFERENCES [dbo].[County] ([CountyNbr])
) ON [AGENCYCD];

