CREATE TABLE [dbo].[AgentAdditionalDetails] (
    [AgentAdditionalDetailsId] INT             NOT NULL,
    [AgentId]                  INT             NOT NULL,
    [AgencyNbr]                CHAR (3)        NOT NULL,
    [BranchNbr]                CHAR (3)        NOT NULL,
    [CountyNbr]                CHAR (3)        NOT NULL,
    [AgentNbr]                 CHAR (4)        NOT NULL,
    [CurrentRecordInd]         BIT             NOT NULL,
    [FederalIdentificationNbr] CHAR (9)        NULL,
    [SocialSecurityNbr]        CHAR (9)        NULL,
    [BirthDt]                  DATE            NULL,
    [DeathDt]                  DATE            NULL,
    [MaritalStatusCd]          CHAR (1)        NULL,
    [MUBonusPct]               DECIMAL (5, 2)  NULL,
    [FBBonusPct]               DECIMAL (5, 2)  NULL,
    [CombinedBonusPct]         DECIMAL (5, 2)  NULL,
    [RetirementPlanInd]        CHAR (1)        NULL,
    [RetirementTotalAmt]       DECIMAL (10, 2) NULL,
    [RetirementBalanceAmt]     DECIMAL (10, 2) NULL,
    [RetirementPaymentsCnt]    INT             NULL,
    [FinanceInd]               CHAR (1)        NULL,
    [BCBSPlanInd]              CHAR (1)        NULL,
    [SFBLPlanInd]              CHAR (1)        NULL,
    [SupplementalPlanInd]      CHAR (1)        NULL,
    [CommissionReductionAmt]   DECIMAL (10, 2) NULL,
    [CommissionReductionDt]    DATE            NULL,
    [SecuritiesDt]             DATE            NULL,
    [BenefitAmt]               DECIMAL (10, 2) NULL,
    [BenefitTypeCd]            CHAR (1)        NULL,
    [IncorporationDt]          DATE            NULL,
    [SFBContractDt]            DATE            NULL,
    [ContractTypeInd]          CHAR (1)        NULL,
    [ContractDt]               DATE            NULL,
    [DeferredTermBalanceAmt]   DECIMAL (10, 2) NULL,
    [DeferredTermPaymentsCnt]  INT             NULL,
    [DeferredTermTotalAmt]     DECIMAL (10, 2) NULL,
    [DeferredTermTypeCd]       CHAR (1)        NULL,
    [UpdatedTmstmp]            DATETIME2 (7)   NOT NULL,
    [UserUpdatedId]            CHAR (8)        NOT NULL,
    [LastActionCd]             CHAR (1)        NOT NULL,
    [SourceSystemCd]           CHAR (2)        NOT NULL,
    CONSTRAINT [PK_AgentAdditionalDetails] PRIMARY KEY CLUSTERED ([AgentAdditionalDetailsId] ASC) ON [AGENCYCD],
    CONSTRAINT [FK_AgentAdditionalDetails_Agency_01] FOREIGN KEY ([AgencyNbr], [CountyNbr], [BranchNbr]) REFERENCES [dbo].[Agency] ([AgencyNbr], [CountyNbr], [BranchNbr]),
    CONSTRAINT [FK_AgentAdditionalDetails_Agent_01] FOREIGN KEY ([AgentId]) REFERENCES [dbo].[Agent] ([AgentId])
) ON [AGENCYCD];

