CREATE TABLE [dbo].[AutoQuote] (
    [QuoteNbr]                      VARCHAR (16)   NOT NULL,
    [SublineBusinessTypeCd]         CHAR (1)       NOT NULL,
    [AgentReceivedDt]               DATE           NULL,
    [HomeOfficeReceivedDt]          DATE           NULL,
    [VehiclesinAccountCnt]          CHAR (3)       NULL,
    [LocationMaxUnitZipCd]          CHAR (9)       NULL,
    [MultiCarVehicleCd]             CHAR (1)       NULL,
    [PassiveRestraintMinimumUnitCd] CHAR (1)       NULL,
    [PIP_MEDSymbolMaxCd]            CHAR (3)       NULL,
    [RateDt]                        DATE           NULL,
    [SubRatePlanCd]                 CHAR (1)       NULL,
    [TerritoryMaxUnitCd]            CHAR (3)       NULL,
    [NoFaultOptionCd]               CHAR (1)       NULL,
    [PreferedSingleUnitAutoInd]     CHAR (1)       NULL,
    [PolicyLegacyDiscountPct]       DECIMAL (3, 2) NULL,
    [PropertyDiscountFormCd]        CHAR (10)      NULL,
    [PNIFarmInd]                    CHAR (1)       NULL,
    [OverrideSubRatePlanCd]         CHAR (1)       NULL,
    [OverrideDesc]                  VARCHAR (255)  NULL,
    [MotorcycleAssociationDesc]     VARCHAR (100)  NULL,
    [StudentOrganizationDesc]       VARCHAR (100)  NULL,
    [FarmPolicyFormCd]              VARCHAR (10)   NULL,
    [MobileHomePolicyFormCd]        VARCHAR (10)   NULL,
    [HomePolicyFormCd]              VARCHAR (10)   NULL,
    [PolicyTypeCd]                  CHAR (1)       NULL,
    [SourceSystemCd]                CHAR (2)       NOT NULL,
    [UpdatedTmstmp]                 DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]                 CHAR (8)       NOT NULL,
    [LastActionCd]                  CHAR (1)       NOT NULL,
    CONSTRAINT [PK_AutoQuote] PRIMARY KEY CLUSTERED ([QuoteNbr] ASC) ON [POLICYCD],
    CONSTRAINT [FK_AutoQuote_Quote_01] FOREIGN KEY ([QuoteNbr]) REFERENCES [dbo].[Quote] ([QuoteNbr])
) ON [POLICYCD];

