CREATE TABLE [dbo].[AutoQuoteUnitPredictiveModel] (
    [QuoteNbr]                            VARCHAR (16)  NOT NULL,
    [QuoteUnitNbr]                        INT           NOT NULL,
    [SublineBusinessTypeCd]               CHAR (1)      NOT NULL,
    [VehicleTierCalculatedNbr]            CHAR (3)      NULL,
    [VehicleTierOverrideNbr]              CHAR (3)      NULL,
    [VehicleTierOverrideExplanationCd]    CHAR (2)      NULL,
    [VehicleTierOverrideExplanationDesc]  CHAR (60)     NULL,
    [OverrideUserAgencyNbr]               CHAR (3)      NULL,
    [OverrideUserID]                      CHAR (8)      NULL,
    [VehicleTierConversionNbr]            CHAR (3)      NULL,
    [ActivePropertyPMCd]                  CHAR (1)      NULL,
    [BodilyInjuryCoverageLimitPMCd]       CHAR (3)      NULL,
    [BodilyInjuryCoverageLimitPointNumbe] INT           NULL,
    [MultiCarPMCd]                        CHAR (1)      NULL,
    [CancelledPoliciesPointNbr]           INT           NULL,
    [DriverAgePointNbr]                   INT           NULL,
    [InsuranceScorePointNbr]              INT           NULL,
    [InceptionMonthsCnt]                  INT           NULL,
    [FaultAccidentCnt]                    INT           NULL,
    [FaultAccidentPointNbr]               INT           NULL,
    [LastAtFaultAccidentDaysCnt]          INT           NULL,
    [LastAtFaultAccidentDaysPointNbr]     INT           NULL,
    [MinorViolationCnt]                   INT           NULL,
    [MinorViolationPointNbr]              INT           NULL,
    [TotalDiscountsCnt]                   INT           NULL,
    [TotalDiscountsPointNbr]              INT           NULL,
    [TotalVehiclePointCnt]                INT           NULL,
    [VehicleAgeYearsNbr]                  INT           NULL,
    [VehicleAgeYearsPointNbr]             INT           NULL,
    [VehiclesvsDriversPointNbr]           INT           NULL,
    [VehicleYearPMDt]                     CHAR (4)      NULL,
    [VehicleTypePMCd]                     CHAR (1)      NULL,
    [AutoCollisionCoverageInd]            CHAR (1)      NULL,
    [UpdatedTmstmp]                       DATETIME2 (7) NOT NULL,
    [UserUpdatedId]                       CHAR (8)      NOT NULL,
    [LastActionCd]                        CHAR (1)      NOT NULL,
    [SourceSystemCd]                      CHAR (2)      NOT NULL,
    CONSTRAINT [PK_AutoQuoteUnitPredictiveModel] PRIMARY KEY CLUSTERED ([QuoteNbr] ASC, [QuoteUnitNbr] ASC) ON [POLICYCD],
    CONSTRAINT [FK_AutoQuoteUnitPredictiveModel_AutoQuoteUnit_01] FOREIGN KEY ([QuoteNbr], [QuoteUnitNbr]) REFERENCES [dbo].[AutoQuoteUnit] ([QuoteNbr], [UnitNbr])
) ON [POLICYCD];

