CREATE TABLE [dbo].[AutoPolicy] (
    [PolicyId]                      INT           NOT NULL,
    [PolicyNbr]                     VARCHAR (16)  NOT NULL,
    [SublineBusinessTypeCd]         CHAR (1)      NOT NULL,
    [AssignedRiskInd]               CHAR (1)      NULL,
    [AgentReceivedDt]               DATE          NULL,
    [AgentTierReviewInd]            CHAR (1)      NULL,
    [HomeOfficeReceivedDt]          DATE          NULL,
    [PriorProcessingDt]             DATE          NULL,
    [ProofOfInsuranceExpirationDt]  DATE          NULL,
    [Term35EffectiveDt]             DATE          NULL,
    [Term35ExpirationDt]            DATE          NULL,
    [VehiclesinAccountCnt]          CHAR (3)      NULL,
    [LocationMaxUnitZipCd]          CHAR (9)      NULL,
    [MultiCarVehicleCd]             CHAR (1)      NULL,
    [PassiveRestraintMinimumUnitCd] CHAR (1)      NULL,
    [PIPMEDSymbolMaxCd]             CHAR (3)      NULL,
    [RateDt]                        DATE          NULL,
    [PreferedSUAInd]                CHAR (1)      NULL,
    [SubRatePlanCd]                 CHAR (1)      NULL,
    [TerritoryMaxUnitCd]            CHAR (3)      NULL,
    [NoFaultOptionCd]               CHAR (1)      NULL,
    [AutoClueOrderedInd]            CHAR (1)      NULL,
    [InsuranceScoreOrderedInd]      CHAR (1)      NULL,
    [MVROrderedInd]                 CHAR (1)      NULL,
    [PropertyDiscountFormCd]        CHAR (10)     NULL,
    [PNIFarmInd]                    CHAR (1)      NULL,
    [OverrideSubRatePlanCd]         CHAR (1)      NULL,
    [OverrideDesc]                  VARCHAR (255) NULL,
    [MotorcycleAssociationDesc]     VARCHAR (100) NULL,
    [StudentOrganizationDesc]       VARCHAR (100) NULL,
    [HomePolicyFormCd]              VARCHAR (10)  NULL,
    [FarmPolicyFormCd]              VARCHAR (10)  NULL,
    [MobileHomePolicyFormCd]        VARCHAR (10)  NULL,
    [PolicyTypeCd]                  CHAR (1)      NULL,
    [CancelCountExcludeCd]          INT           NULL,
    [CancelCountExcludeDesc]        VARCHAR (60)  NULL,
    [CancelExcludeUpdatedTmstmp]    DATETIME2 (7) NULL,
    [SourceSystemCd]                CHAR (2)      NOT NULL,
    [UpdatedTmstmp]                 DATETIME2 (7) NOT NULL,
    [UserUpdatedId]                 CHAR (8)      NOT NULL,
    [LastActionCd]                  CHAR (1)      NOT NULL,
    CONSTRAINT [PK_AutoPolicy] PRIMARY KEY CLUSTERED ([PolicyId] ASC) ON [POLICYCD],
    CONSTRAINT [FK_AutoPolicy_Policy_01] FOREIGN KEY ([PolicyId]) REFERENCES [dbo].[Policy] ([PolicyId])
) ON [POLICYCD];

