CREATE TABLE [dbo].[AutoQuoteDriver] (
    [QuoteNbr]                                     VARCHAR (16)   NOT NULL,
    [UnitNbr]                                      INT            NOT NULL,
    [QuotePartyRelationId]                         INT            NOT NULL,
    [SublineBusinessTypeCd]                        CHAR (1)       NOT NULL,
    [DriverNbr]                                    CHAR (3)       NULL,
    [ClientReferenceNbr]                           CHAR (10)      NULL,
    [AssignedDriverInd]                            CHAR (1)       NULL,
    [PrincipalOperatorCd]                          CHAR (1)       NULL,
    [DriverNm]                                     VARCHAR (100)  NULL,
    [DriverBirthDt]                                DATE           NULL,
    [GenderCd]                                     CHAR (1)       NULL,
    [MaritalStatusCd]                              CHAR (1)       NULL,
    [LicenseNbr]                                   CHAR (25)      NULL,
    [LicenseStateCd]                               CHAR (2)       NULL,
    [MVRCd]                                        CHAR (1)       NULL,
    [MVRReceivedDt]                                DATE           NULL,
    [MVRRequestDt]                                 DATE           NULL,
    [CLUEReportReferenceNbr]                       CHAR (14)      NULL,
    [DriverClassCd]                                CHAR (3)       NULL,
    [ClassOverrideInd]                             CHAR (1)       NULL,
    [DriverTrainingInd]                            CHAR (1)       NULL,
    [OccupationDesc]                               VARCHAR (60)   NULL,
    [BusDriverInd]                                 CHAR (1)       NULL,
    [GovernmentVehicleDriverInd]                   CHAR (1)       NULL,
    [MilitaryDriverInd]                            CHAR (1)       NULL,
    [DefensiveDriverInd]                           CHAR (1)       NULL,
    [GoodStudentInd]                               CHAR (1)       NULL,
    [StateTrooperInd]                              CHAR (1)       NULL,
    [RecertificationPendingInd]                    CHAR (1)       NULL,
    [RecertificationPendingBusDriverInd]           CHAR (1)       NULL,
    [RecertificationBusDriverDt]                   DATE           NULL,
    [RecertificationPendingDefensiveDriverInd]     CHAR (1)       NULL,
    [RecertificationDefensiveDriverDt]             DATE           NULL,
    [RecertificationPendingGoodStudentInd]         CHAR (1)       NULL,
    [RecertificationGoodStudentDt]                 DATE           NULL,
    [RecertificationPendingMilitaryInd]            CHAR (1)       NULL,
    [RecertificationMilitaryDt]                    DATE           NULL,
    [DriveRightDiscountCd]                         CHAR (2)       NULL,
    [DriveRightDiscountDesc]                       VARCHAR (100)  NULL,
    [DriveRightDiscountPct]                        DECIMAL (3, 2) NULL,
    [DriveRightDiscountDt]                         DATE           NULL,
    [FutureDriveRightDiscountPct]                  DECIMAL (3, 2) NULL,
    [FutureDriveRightDiscountRenewalEligibilityDt] DATE           NULL,
    [YearsDriverLicencedCnt]                       INT            NULL,
    [Last5yearimpairmentInd]                       CHAR (1)       NULL,
    [EmploymentDesc]                               VARCHAR (255)  NULL,
    [MotorcycleLicenseInd]                         CHAR (1)       NULL,
    [DriveRightMobileInd]                          CHAR (1)       NULL,
    [UpdatedTmstmp]                                DATETIME2 (7)  NOT NULL,
    [TotalTrips]                                   DECIMAL (5)    NULL,
    [UserUpdatedId]                                CHAR (8)       NOT NULL,
    [LastActionCd]                                 CHAR (1)       NOT NULL,
    [SourceSystemCd]                               CHAR (2)       NOT NULL,
    CONSTRAINT [PK_AutoQuoteDriver] PRIMARY KEY CLUSTERED ([QuoteNbr] ASC, [UnitNbr] ASC, [QuotePartyRelationId] ASC) ON [POLICYCD],
    CONSTRAINT [FK_AutoQuoteUnit_AutoQuoteDriver_01] FOREIGN KEY ([QuoteNbr], [UnitNbr]) REFERENCES [dbo].[AutoQuoteUnit] ([QuoteNbr], [UnitNbr]),
    CONSTRAINT [FK_QuotePartyRelation_AutoQuoteDriver_01] FOREIGN KEY ([QuotePartyRelationId]) REFERENCES [dbo].[QuotePartyRelation] ([QuotePartyRelationId])
) ON [POLICYCD];


GO
CREATE NONCLUSTERED INDEX [IX_AutoQuoteDriver_01]
    ON [dbo].[AutoQuoteDriver]([QuoteNbr] ASC)
    ON [POLICYCI];

