CREATE TABLE [dbo].[AutoQuotePredictiveModel] (
    [QuoteNbr]                          VARCHAR (16)  NOT NULL,
    [SublineBusinessTypeCd]             CHAR (1)      NOT NULL,
    [PolicyTierCalculatedNbr]           CHAR (3)      NULL,
    [PolicyTierOverrideNbr]             CHAR (3)      NULL,
    [TierConversionNbr]                 CHAR (3)      NULL,
    [PolicyTierOverrideExplanationCd]   CHAR (2)      NULL,
    [PolicyTierOverrideExplanationDesc] CHAR (60)     NULL,
    [OverrideUserAgencyNbr]             CHAR (3)      NULL,
    [OverrideUserID]                    CHAR (8)      NULL,
    [InsuranceScoreNbr]                 INT           NULL,
    [MembershipTotalVehicleCnt]         INT           NULL,
    [MembershipTotalDriverCnt]          INT           NULL,
    [CancelledPoliciesCnt]              INT           NULL,
    [TimeSinceInceptionMonthsCnt]       INT           NULL,
    [DriverAgeCnt]                      INT           NULL,
    [InsuranceScoreRelationshipCd]      CHAR (2)      NULL,
    [VehiclesvsDriversCd]               CHAR (2)      NULL,
    [PolicyPredictiveModelTypeCd]       CHAR (3)      NULL,
    [ActivePropertyFormCd]              CHAR (4)      NULL,
    [ActivePropertyFormPointNbr]        INT           NULL,
    [UpdatedTmstmp]                     DATETIME2 (7) NOT NULL,
    [UserUpdatedId]                     CHAR (8)      NOT NULL,
    [LastActionCd]                      CHAR (1)      NOT NULL,
    [SourceSystemCd]                    CHAR (2)      NOT NULL,
    CONSTRAINT [PK_AutoQuotePredictiveModel] PRIMARY KEY CLUSTERED ([QuoteNbr] ASC) ON [POLICYCD],
    CONSTRAINT [FK_AutoQuotePredictiveModel_AutoQuote_01] FOREIGN KEY ([QuoteNbr]) REFERENCES [dbo].[AutoQuote] ([QuoteNbr])
) ON [POLICYCD];

