CREATE TABLE [dbo].[AutoUnitPredictiveModel] (
    [PolicyId]                           INT           NOT NULL,
    [UnitNbr]                            INT           NOT NULL,
    [PolicyNbr]                          VARCHAR (16)  NOT NULL,
    [SublineBusinessTypeCd]              CHAR (1)      NOT NULL,
    [VehicleTierCalculatedNbr]           CHAR (3)      NULL,
    [VehicleTierOverrideNbr]             CHAR (3)      NULL,
    [VehicleTierOverrideExplanationCd]   CHAR (2)      NULL,
    [VehicleTierOverrideExplanationDesc] CHAR (60)     NULL,
    [OverrideUserAgencyNbr]              CHAR (3)      NULL,
    [OverrideUserID]                     CHAR (8)      NULL,
    [VehicleTierConversionNbr]           CHAR (3)      NULL,
    [UnitMigrationTierInd]               CHAR (1)      NULL,
    [ActivePropertyPMCd]                 CHAR (1)      NULL,
    [BodilyInjuryCoverageLimitPMCd]      CHAR (3)      NULL,
    [BodilyInjuryCoverageLimitPointNbr]  INT           NULL,
    [MultiCarPMCd]                       CHAR (1)      NULL,
    [CancelledPoliciesPointNbr]          INT           NULL,
    [DriverAgePointNbr]                  INT           NULL,
    [InsuranceScorePointNbr]             INT           NULL,
    [InceptionMonthsCnt]                 INT           NULL,
    [FaultAccidentCnt]                   INT           NULL,
    [FaultAccidentPointNbr]              INT           NULL,
    [LastAtFaultAccidentDaysCnt]         INT           NULL,
    [LastAtFaultAccidentDaysPointNbr]    INT           NULL,
    [MinorViolationCnt]                  INT           NULL,
    [MinorViolationPointNbr]             INT           NULL,
    [TotalDiscountsCnt]                  INT           NULL,
    [TotalDiscountsPointNbr]             INT           NULL,
    [TotalVehiclePointCnt]               INT           NULL,
    [VehicleAgeYearsNbr]                 INT           NULL,
    [AutoCollisionCoverageInd]           CHAR (1)      NULL,
    [VehicleAgeYearsPointNbr]            INT           NULL,
    [VehiclesvsDriversPointNbr]          INT           NULL,
    [VehicleYearPMDt]                    CHAR (4)      NULL,
    [VehicleTypePMCd]                    CHAR (1)      NULL,
    [UpdatedTmstmp]                      DATETIME2 (7) NOT NULL,
    [UserUpdatedId]                      CHAR (8)      NOT NULL,
    [LastActionCd]                       CHAR (1)      NOT NULL,
    [SourceSystemCd]                     CHAR (2)      NOT NULL,
    CONSTRAINT [PK_AutoUnitPredictiveModel] PRIMARY KEY CLUSTERED ([PolicyId] ASC, [UnitNbr] ASC) ON [POLICYCD],
    CONSTRAINT [FK_AutoUnitPredictiveModel_AutoUnit_01] FOREIGN KEY ([PolicyId], [UnitNbr]) REFERENCES [dbo].[AutoUnit] ([PolicyId], [UnitNbr])
) ON [POLICYCD];

