CREATE TABLE [dbo].[Billing] (
    [BillId]                         INT            NOT NULL,
    [CurrentRecordInd]               BIT            NOT NULL,
    [PolicyNbr]                      VARCHAR (16)   NOT NULL,
    [TermNbr]                        INT            NULL,
    [TermEffectiveDt]                DATE           NULL,
    [TermExpiryDt]                   DATE           NULL,
    [AccountBillNbr]                 CHAR (10)      NULL,
    [BillCd]                         CHAR (2)       NULL,
    [BillPlanCd]                     CHAR (2)       NULL,
    [BillToCd]                       CHAR (1)       NULL,
    [PremiumDueAmt]                  DECIMAL (9, 2) NULL,
    [BilledMinimumDueAmt]            DECIMAL (9, 2) NULL,
    [PreviousMinimumDueAmt]          DECIMAL (9, 2) NULL,
    [DueDt]                          DATE           NULL,
    [ExtendedDueDt]                  DATE           NULL,
    [DueReasonCd]                    CHAR (2)       NULL,
    [Billed02MonthsDueAmt]           DECIMAL (9, 2) NULL,
    [Billed03MonthsDueAmt]           DECIMAL (9, 2) NULL,
    [CarryDt]                        DATE           NULL,
    [TimesToBillCnt]                 INT            NULL,
    [TimesBilledCnt]                 INT            NULL,
    [TotalBillAmtCd]                 CHAR (1)       NULL,
    [InstallmentBillAmt]             DECIMAL (9, 2) NULL,
    [InstallmentServiceChargeAmt]    DECIMAL (9, 2) NULL,
    [InstallmentServiceSurchargeAmt] DECIMAL (9, 2) NULL,
    [InstallmentActiveCd]            CHAR (1)       NULL,
    [InstallmentEligibleInd]         CHAR (1)       NULL,
    [LateFeeAmt]                     DECIMAL (9, 2) NULL,
    [LateFeeSurchargeAmt]            DECIMAL (9, 2) NULL,
    [LatePayCnt]                     INT            NULL,
    [NSFFeeAmt]                      DECIMAL (9, 2) NULL,
    [NSFFeeSurchargeAmt]             DECIMAL (9, 2) NULL,
    [NSFCnt]                         INT            NULL,
    [ReinstatementFeeAmt]            DECIMAL (9, 2) NULL,
    [ReinstatementFeeSurchargeAmt]   DECIMAL (9, 2) NULL,
    [DueAtCancellationAmt]           DECIMAL (9, 2) NULL,
    [ShortPaidCnt]                   INT            NULL,
    [DenyShortPaymentCd]             VARCHAR (30)   NULL,
    [TermTotalPaidAmt]               DECIMAL (9, 2) NULL,
    [TermTotalRefundAmt]             DECIMAL (9, 2) NULL,
    [AccountBillPendingActionCd]     CHAR (2)       NULL,
    [AccountBillChangeEffectiveDt]   DATE           NULL,
    [AccountBillReasonCd]            CHAR (2)       NULL,
    [LastRefundAppliedPolicyNbr]     CHAR (16)      NULL,
    [UpdatedTmstmp]                  DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]                  CHAR (8)       NOT NULL,
    [LastActionCd]                   CHAR (1)       NOT NULL,
    [SourceSystemCd]                 CHAR (2)       NOT NULL,
    CONSTRAINT [PK_Billing] PRIMARY KEY CLUSTERED ([BillId] ASC) ON [POLICYCD]
) ON [POLICYCD];

