CREATE TABLE [dbo].[Catastrophe] (
    [CatastropheNbr]             CHAR (10)     NOT NULL,
    [CatastropheTypeId]          INT           NOT NULL,
    [CatastropheDesc]            CHAR (50)     NULL,
    [CatastropheStartDt]         DATE          NOT NULL,
    [CatastropheEndDt]           DATE          NULL,
    [UpdatedTmstmp]              DATETIME2 (7) NOT NULL,
    [UserUpdatedId]              CHAR (8)      NOT NULL,
    [LastActionCd]               CHAR (1)      NOT NULL,
    [SourceSystemCd]             CHAR (2)      NOT NULL,
    [ClaimUserCreateTime]        DATETIME2 (7) NOT NULL,
    [ClaimUserCreatedId]         CHAR (8)      NOT NULL,
    [ClaimUserUpdatedId]         CHAR (8)      NOT NULL,
    [ClaimUpdatedTmstmp]         DATETIME2 (7) NOT NULL,
    [CurrentRecordInd]           BIT           NOT NULL,
    [RetiredInd]                 CHAR (1)      NOT NULL,
    [SourceSystemId]             INT           NOT NULL,
    [ValidFromDt]                DATE          NULL,
    [ValidToDt]                  DATE          NULL,
    [AutoSendEstAssignmentInd]   CHAR (1)      NULL,
    [GenerateCatnoticeInd]       CHAR (1)      NULL,
    [NumofDaysFirstCatnoticeId]  INT           NULL,
    [PowerOutageInd]             CHAR (1)      NULL,
    [NumofDaysSecondCatnoticeId] INT           NULL,
    [AutomaticActionInd]         CHAR (1)      NULL,
    [Name]                       VARCHAR (60)  NULL,
    CONSTRAINT [PK_Catastrophe] PRIMARY KEY CLUSTERED ([CatastropheNbr] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_Catastrophe_ClaimCodeLookup_01] FOREIGN KEY ([NumofDaysFirstCatnoticeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Catastrophe_ClaimCodeLookup_02] FOREIGN KEY ([NumofDaysSecondCatnoticeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Catastrophe_ClaimCodeLookup_03] FOREIGN KEY ([CatastropheTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId])
) ON [CLAIMSCD];

