CREATE TABLE [dbo].[ClaimPolicy] (
    [ClaimPolicyId]                  INT             NOT NULL,
    [SMPPolicyTypeId]                INT             NULL,
    [FarmPolicyTypeId]               INT             NULL,
    [PolicyStatusId]                 INT             NULL,
    [AnchoredId]                     INT             NULL,
    [OLPolicyTypeId]                 INT             NULL,
    [PolicyFormId]                   INT             NULL,
    [SubLineBusinessId]              INT             NULL,
    [FireTypePolicyId]               INT             NULL,
    [CentralHeatId]                  INT             NULL,
    [PolicyTypeId]                   INT             NOT NULL,
    [FireRateTypeId]                 INT             NULL,
    [ProgramCodeId]                  INT             NULL,
    [PolicySourceId]                 INT             NULL,
    [EOAgentNbr]                     CHAR (4)        NULL,
    [AgentNbr]                       CHAR (4)        NULL,
    [RenewalAgencyNbr]               CHAR (3)        NULL,
    [DeductibleType]                 CHAR (2)        NULL,
    [StatCovInd]                     CHAR (1)        NULL,
    [ChangeEffectiveDt]              DATE            NULL,
    [SMPPolicyLimit]                 CHAR (1)        NULL,
    [ClassCd]                        VARCHAR (5)     NULL,
    [MainDwellingNbr]                INT             NULL,
    [RatingTerritoryCd]              CHAR (2)        NULL,
    [InflationGuardCd]               CHAR (1)        NULL,
    [MobileHomeUnitWidthNbr]         INT             NULL,
    [ExtendedDueDt]                  DATE            NULL,
    [WindCoverageCd]                 VARCHAR (3)     NULL,
    [DeductibleCd]                   CHAR (1)        NULL,
    [MobileHomePurchaseDt]           VARCHAR (6)     NULL,
    [PersonNamedInPolicyNbr]         VARCHAR (2)     NULL,
    [ZoneCd]                         VARCHAR (2)     NULL,
    [AdditionalInsuredNbr]           INT             NULL,
    [ManufacturedHomeInd]            CHAR (1)        NULL,
    [MHLengthNbr]                    INT             NULL,
    [OrigEffectiveDt]                DATE            NULL,
    [TotalFarmSitesNbr]              INT             NULL,
    [ParkCourtInd]                   CHAR (1)        NULL,
    [CarryDt]                        DATE            NULL,
    [LineCd]                         VARCHAR (3)     NULL,
    [ConstnYearDt]                   VARCHAR (4)     NULL,
    [SubRatePlanCd]                  VARCHAR (1)     NULL,
    [LiabilityClassCd]               VARCHAR (5)     NULL,
    [CancellationDt]                 DATE            NULL,
    [MHMakeDesc]                     VARCHAR (11)    NULL,
    [RateClassCd]                    VARCHAR (4)     NULL,
    [ExpirationDt]                   DATE            NULL,
    [WindClassCd]                    VARCHAR (3)     NULL,
    [ProtectionClassCd]              VARCHAR (2)     NULL,
    [ManufacturedHomeMakeDesc]       VARCHAR (11)    NULL,
    [BIPDAggregateAmt]               DECIMAL (18, 2) NULL,
    [ConstructionTypeCd]             VARCHAR (2)     NULL,
    [ManWorkDaysNbr]                 INT             NULL,
    [IRPMClaimsPercentFctr]          DECIMAL (6, 3)  NULL,
    [CoverageChangeEffectiveDt]      DATE            NULL,
    [PhysicalCharLiabilityCd]        CHAR (10)       NULL,
    [IRPMPhysicalConditionFctr]      DECIMAL (9, 9)  NULL,
    [TotalPropertiesCnt]             INT             NULL,
    [EffectiveDt]                    DATE            NULL,
    [MHPriceNew]                     VARCHAR (6)     NULL,
    [AdditionalResidenceNbr]         INT             NULL,
    [OccupancyTypeCd]                CHAR (1)        NULL,
    [ManufacturedHomeSerNbr]         VARCHAR (9)     NULL,
    [PolicyLevelOccupancyCd]         CHAR (1)        NULL,
    [SprinklerSystemId]              CHAR (1)        NULL,
    [PolicyTermNbr]                  INT             NULL,
    [SuburbanClassCd]                CHAR (1)        NULL,
    [AcresNbr]                       INT             NULL,
    [CategoryCd]                     CHAR (2)        NULL,
    [QuotaShareCd]                   CHAR (2)        NULL,
    [SelfInsuredRetentionAmt]        INT             NULL,
    [ManurePitsNbr]                  INT             NULL,
    [ManufacturingUnitSerialNbr]     VARCHAR (10)    NULL,
    [CompanyNbr]                     VARCHAR (3)     NULL,
    [PolicyNumber]                   VARCHAR (40)    NOT NULL,
    [PollutionReferenceInd]          CHAR (1)        NULL,
    [PolicyDeductibleAmt]            DECIMAL (18, 2) NULL,
    [ExposureMonthNbr]               INT             NULL,
    [LocationZipCd]                  VARCHAR (9)     NULL,
    [NumberOfApartmentNbr]           INT             NULL,
    [SmokeAlarmInd]                  CHAR (1)        NULL,
    [CovOptCrimeCd]                  VARCHAR (2)     NULL,
    [RenewalBranchNbr]               VARCHAR (3)     NULL,
    [BookofBusinessAmt]              DECIMAL (18, 2) NULL,
    [FamiliesNbr]                    INT             NULL,
    [NonBookofBusinessAmt]           DECIMAL (18, 2) NULL,
    [UndergroundTanksNbr]            INT             NULL,
    [PremiumGroupCd]                 VARCHAR (2)     NULL,
    [ActivePropertyCd]               CHAR (1)        NULL,
    [ExposureBaseAmt]                DECIMAL (18, 2) NULL,
    [IMClassCd]                      CHAR (7)        NULL,
    [CashUnitNbr]                    CHAR (3)        NULL,
    [FoundationCd]                   CHAR (1)        NULL,
    [TotalLiabilityLocationNbr]      VARCHAR (2)     NULL,
    [PolicyEditionDt]                VARCHAR (5)     NULL,
    [SPRCd]                          VARCHAR (8)     NULL,
    [FireClassCd]                    VARCHAR (5)     NULL,
    [SpecialFarmOwnerDiscountAmt]    DECIMAL (18, 2) NULL,
    [SpecialWindHailDeductibleAmt]   DECIMAL (18, 2) NULL,
    [MultiJurisdictInd]              CHAR (1)        NULL,
    [MultiJurisdictMsgDesc]          VARCHAR (255)   NULL,
    [PolicyTierOverrideCd]           VARCHAR (3)     NULL,
    [VehicleUnitNbr]                 INT             NULL,
    [PolicyTierCd]                   VARCHAR (3)     NULL,
    [PolicyTierConversionOverrideCd] VARCHAR (3)     NULL,
    [PolicyLimitAmt]                 DECIMAL (18, 2) NULL,
    [AssignedRiskCd]                 CHAR (1)        NULL,
    [PolicyRevisionId]               INT             NULL,
    [UpdatedTmstmp]                  DATETIME2 (7)   NOT NULL,
    [UserUpdatedId]                  CHAR (8)        NOT NULL,
    [LastActionCd]                   CHAR (1)        NOT NULL,
    [SourceSystemCd]                 CHAR (2)        NOT NULL,
    [SourceSystemId]                 INT             NOT NULL,
    [PCConversionDt]                 DATE            NULL,
    [ClaimUserCreateTime]            DATETIME2 (7)   NOT NULL,
    [ClaimUserCreatedId]             CHAR (8)        NOT NULL,
    [ClaimUserUpdatedId]             CHAR (8)        NOT NULL,
    [ClaimUpdatedTmstmp]             DATETIME2 (7)   NOT NULL,
    [PreferredSUAInd]                CHAR (1)        NULL,
    [CreditScoreStat]                VARCHAR (2)     NULL,
    [CurrentRecordInd]               BIT             NOT NULL,
    [RetiredInd]                     CHAR (1)        NOT NULL,
    [ExceptionCd1]                   CHAR (1)        NULL,
    [ExceptionCd2]                   CHAR (1)        NULL,
    [ExceptionCd3]                   CHAR (1)        NULL,
    [ExceptionCd4]                   CHAR (1)        NULL,
    [ExceptionCd5]                   CHAR (1)        NULL,
    [CountyNbr]                      CHAR (3)        NULL,
    [LocationCountyNbr]              CHAR (3)        NULL,
    [MiscDInd]                       CHAR (1)        NULL,
    [EQEndorsementInd]               CHAR (1)        NULL,
    CONSTRAINT [PK_ClaimPolicy] PRIMARY KEY CLUSTERED ([ClaimPolicyId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_ClaimPolicy_ClaimCodeLookup_01] FOREIGN KEY ([SMPPolicyTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimPolicy_ClaimCodeLookup_02] FOREIGN KEY ([FarmPolicyTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimPolicy_ClaimCodeLookup_03] FOREIGN KEY ([PolicyStatusId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimPolicy_ClaimCodeLookup_04] FOREIGN KEY ([AnchoredId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimPolicy_ClaimCodeLookup_05] FOREIGN KEY ([OLPolicyTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimPolicy_ClaimCodeLookup_06] FOREIGN KEY ([PolicyFormId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimPolicy_ClaimCodeLookup_07] FOREIGN KEY ([SubLineBusinessId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimPolicy_ClaimCodeLookup_08] FOREIGN KEY ([FireTypePolicyId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimPolicy_ClaimCodeLookup_09] FOREIGN KEY ([CentralHeatId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimPolicy_ClaimCodeLookup_10] FOREIGN KEY ([PolicyTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimPolicy_ClaimCodeLookup_11] FOREIGN KEY ([FireRateTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimPolicy_ClaimCodeLookup_12] FOREIGN KEY ([ProgramCodeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimPolicy_ClaimCodeLookup_13] FOREIGN KEY ([PolicySourceId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId])
) ON [CLAIMSCD];

