CREATE TABLE [dbo].[ClaimActivity] (
    [ClaimActivityId]           INT           NOT NULL,
    [ActivityCategoryId]        INT           NULL,
    [ClaimLossTypeId]           INT           NULL,
    [ImportanceLevelId]         INT           NULL,
    [PriorityId]                INT           NULL,
    [ActivityTypeId]            INT           NULL,
    [ActivityClassId]           INT           NULL,
    [AssignmentStatusId]        INT           NULL,
    [ClaimNbr]                  CHAR (10)     NOT NULL,
    [ExposureNbr]               CHAR (10)     NOT NULL,
    [ClaimBranchNbr]            CHAR (3)      NOT NULL,
    [ClientReferenceNbr]        CHAR (10)     NOT NULL,
    [ActivityCd]                VARCHAR (60)  NULL,
    [ClosedClaimAvailableInd]   CHAR (1)      NULL,
    [ExternallyOwnedInd]        CHAR (1)      NULL,
    [MandatoryInd]              CHAR (1)      NULL,
    [ApprovedInd]               CHAR (1)      NULL,
    [EscalatedInd]              CHAR (1)      NULL,
    [LitigationInd]             CHAR (1)      NULL,
    [GeneralLitigationInd]      CHAR (1)      NULL,
    [SendAssignmentInd]         CHAR (1)      NULL,
    [SubrogationInd]            CHAR (1)      NULL,
    [RetiredInd]                CHAR (1)      NULL,
    [SIUInd]                    CHAR (1)      NULL,
    [CurrentRecordInd]          BIT           NOT NULL,
    [AssignmentDt]              DATE          NULL,
    [ClosedDt]                  DATE          NULL,
    [EscalationDt]              DATE          NULL,
    [TargetDt]                  DATE          NULL,
    [LastViewedDt]              DATE          NULL,
    [ShortSubjectDesc]          VARCHAR (255) NULL,
    [SubjectDesc]               VARCHAR (255) NOT NULL,
    [ApprovalIssueDesc]         VARCHAR (255) NOT NULL,
    [ActivityDesc]              VARCHAR (255) NOT NULL,
    [ApprovalRationaleDesc]     VARCHAR (255) NOT NULL,
    [AssignedID]                CHAR (8)      NOT NULL,
    [ExternalOwnerID]           CHAR (8)      NOT NULL,
    [DocumentOwnerID]           CHAR (8)      NOT NULL,
    [SourceSystemId]            INT           NOT NULL,
    [SourceSystemUserCreatedId] CHAR (10)     NULL,
    [SourceSystemCreatedTmstmp] DATETIME2 (7) NULL,
    [SourceSystemUserUpdatedId] CHAR (10)     NOT NULL,
    [SourceSystemUpdatedTmstmp] DATETIME2 (7) NULL,
    [UserUpdatedId]             CHAR (8)      NOT NULL,
    [UpdatedTmstmp]             DATETIME2 (7) NOT NULL,
    [SourceSystemCd]            CHAR (2)      NOT NULL,
    [LastActionCd]              CHAR (1)      NOT NULL,
    CONSTRAINT [PK_ClaimActivity] PRIMARY KEY CLUSTERED ([ClaimActivityId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_ClaimActivity_ClaimCodeLookup_01] FOREIGN KEY ([ActivityCategoryId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimActivity_ClaimCodeLookup_02] FOREIGN KEY ([ClaimLossTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimActivity_ClaimCodeLookup_03] FOREIGN KEY ([ImportanceLevelId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimActivity_ClaimCodeLookup_04] FOREIGN KEY ([PriorityId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimActivity_ClaimCodeLookup_05] FOREIGN KEY ([ActivityTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimActivity_ClaimCodeLookup_06] FOREIGN KEY ([ActivityClassId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimActivity_ClaimCodeLookup_07] FOREIGN KEY ([AssignmentStatusId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId])
) ON [CLAIMSCD];

