CREATE TABLE [dbo].[ClaimGroup] (
    [ClaimGroupId]        INT           NOT NULL,
    [SupervisorUserId]    CHAR (8)      NULL,
    [ParentClaimGroupId]  INT           NULL,
    [AgencyAllClaimInd]   CHAR (1)      NOT NULL,
    [ClaimBranchNbr]      CHAR (3)      NULL,
    [AgencyBranchNbr]     VARCHAR (3)   NULL,
    [AgencyName]          VARCHAR (100) NULL,
    [GroupName]           CHAR (100)    NULL,
    [GroupTypeId]         INT           NOT NULL,
    [ClaimUserCreatedId]  CHAR (8)      NOT NULL,
    [UpdatedTmstmp]       DATETIME2 (7) NOT NULL,
    [ClaimUserCreateTime] DATETIME2 (7) NOT NULL,
    [ClaimUpdatedTmstmp]  DATETIME2 (7) NOT NULL,
    [ClaimUserUpdatedId]  CHAR (8)      NOT NULL,
    [RetiredInd]          CHAR (1)      NOT NULL,
    [SourceSystemId]      INT           NOT NULL,
    [LastActionCd]        CHAR (1)      NOT NULL,
    [UserUpdatedId]       CHAR (8)      NOT NULL,
    [SourceSystemCd]      CHAR (2)      NOT NULL,
    [CurrentRecordInd]    BIT           NOT NULL,
    [RegionId]            INT           NULL,
    CONSTRAINT [PK_ClaimGroup] PRIMARY KEY NONCLUSTERED ([ClaimGroupId] ASC) ON [CLAIMSCD]
) ON [CLAIMSCD];

