CREATE TABLE [dbo].[ClaimExternalAdjuster] (
    [ClaimExternalAdjusterId]          INT           NOT NULL,
    [ExternalAdjusterVendorId]         INT           NULL,
    [InternalAdjusterId]               INT           NULL,
    [PropEstStatusId]                  INT           NULL,
    [XactimateProfileIdCd]             VARCHAR (60)  NULL,
    [XactimateCarrierIdCd]             VARCHAR (10)  NULL,
    [ExternalAdjusterCellPhoneNbr]     CHAR (16)     NULL,
    [ExternalAdjusterEmailAddressDesc] VARCHAR (60)  NULL,
    [ExtenalAdjusterFaxNbr]            CHAR (16)     NULL,
    [ExternalAdjusterNm]               VARCHAR (60)  NULL,
    [ExternalAdjusterWorkPhoneNbr]     CHAR (16)     NULL,
    [CurrentRecordInd]                 BIT           NOT NULL,
    [RetiredInd]                       CHAR (1)      NOT NULL,
    [SourceSystemId]                   INT           NOT NULL,
    [SourceSystemCreatedTmstmp]        DATETIME2 (7) NOT NULL,
    [SourceSystemUserCreatedCd]        CHAR (10)     NOT NULL,
    [SourceSystemUpdatedTmstmp]        DATETIME2 (7) NOT NULL,
    [SourceSystemUserUpdatedCd]        CHAR (10)     NOT NULL,
    [UpdatedTmstmp]                    DATETIME2 (7) NOT NULL,
    [UserUpdatedCd]                    CHAR (10)     NOT NULL,
    [LastActionCd]                     CHAR (1)      NOT NULL,
    [SourceSystemCd]                   CHAR (2)      NOT NULL,
    CONSTRAINT [PK_ClaimExternalAdjuster] PRIMARY KEY CLUSTERED ([ClaimExternalAdjusterId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_ClaimExternalAdjuster_ClaimCodeLookup_01] FOREIGN KEY ([PropEstStatusId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimExternalAdjuster_Party_01] FOREIGN KEY ([ExternalAdjusterVendorId]) REFERENCES [dbo].[Party] ([PartyId]),
    CONSTRAINT [FK_ClaimExternalAdjuster_UserClaimUserRole_01] FOREIGN KEY ([InternalAdjusterId]) REFERENCES [dbo].[UserClaimUserRole] ([UserClaimUserRoleId])
) ON [CLAIMSCD];

