CREATE TABLE [dbo].[ClaimVehicle] (
    [ClaimVehicleId]                  INT           NOT NULL,
    [VehicleStyleId]                  INT           NULL,
    [AntiTheftId]                     INT           NULL,
    [BoatTypeId]                      INT           NULL,
    [CompanyFedId]                    INT           NULL,
    [PackageTypeId]                   INT           NULL,
    [VehicleUseId]                    INT           NULL,
    [ManufacturerId]                  INT           NULL,
    [OffRoadStyleId]                  INT           NULL,
    [RegisteredStateId]               INT           NULL,
    [VINNbr]                          CHAR (40)     NULL,
    [SerialNbr]                       VARCHAR (20)  NULL,
    [VehicleMakeCd]                   CHAR (50)     NULL,
    [VehicleModelNm]                  CHAR (40)     NULL,
    [VehicleYearDt]                   CHAR (4)      NULL,
    [VehicleSymbolCd]                 CHAR (3)      NULL,
    [UpdatedTmstmp]                   DATETIME2 (7) NOT NULL,
    [UserUpdatedId]                   CHAR (8)      NOT NULL,
    [LastActionCd]                    CHAR (1)      NOT NULL,
    [SourceSystemCd]                  CHAR (2)      NOT NULL,
    [SourceSystemId]                  INT           NOT NULL,
    [ClaimUserCreateTime]             DATETIME2 (7) NOT NULL,
    [ClaimUserCreatedId]              CHAR (8)      NOT NULL,
    [ClaimUserUpdatedId]              CHAR (8)      NOT NULL,
    [ClaimUpdatedTmstmp]              DATETIME2 (7) NOT NULL,
    [CurrentRecordInd]                BIT           NOT NULL,
    [RetiredInd]                      CHAR (1)      NOT NULL,
    [VehicleUnitNbr]                  VARCHAR (3)   NULL,
    [AntiLockInd]                     CHAR (1)      NULL,
    [BoatHP]                          INT           NULL,
    [BoatLength]                      CHAR (15)     NULL,
    [BoatPropulsionType]              CHAR (20)     NULL,
    [ClassRiskCd]                     CHAR (7)      NULL,
    [MultiCarInd]                     CHAR (1)      NULL,
    [PassiveRestraintInd]             CHAR (10)     NULL,
    [RatePlanCd]                      CHAR (1)      NULL,
    [SeniorDriverInd]                 CHAR (1)      NULL,
    [SpecialVehCd]                    CHAR (1)      NULL,
    [Color]                           VARCHAR (40)  NULL,
    [AssignedDriverNum]               INT           NULL,
    [BusDriverInd]                    CHAR (1)      NULL,
    [CollRatingSymbolCd]              CHAR (3)      NULL,
    [LiabBIPDSymCd]                   CHAR (3)      NULL,
    [ThirdPartyLoanNum]               VARCHAR (25)  NULL,
    [BodyStyle]                       VARCHAR (55)  NULL,
    [VinVerifiedInd]                  CHAR (1)      NULL,
    [PIPMedSymbolCd]                  VARCHAR (3)   NULL,
    [CompRatingSymbolCd]              VARCHAR (3)   NULL,
    [VehicleTierOverrideCd]           VARCHAR (3)   NULL,
    [VehicleTierCd]                   VARCHAR (3)   NULL,
    [VehicleTierConversionOverrideCd] VARCHAR (3)   NULL,
    CONSTRAINT [PK_ClaimVehicle] PRIMARY KEY CLUSTERED ([ClaimVehicleId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_ClaimVehicle_ClaimCodeLookup_01] FOREIGN KEY ([VehicleStyleId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimVehicle_ClaimCodeLookup_02] FOREIGN KEY ([BoatTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimVehicle_ClaimCodeLookup_03] FOREIGN KEY ([CompanyFedId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimVehicle_ClaimCodeLookup_04] FOREIGN KEY ([PackageTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimVehicle_ClaimCodeLookup_05] FOREIGN KEY ([ManufacturerId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimVehicle_ClaimCodeLookup_06] FOREIGN KEY ([OffRoadStyleId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimVehicle_ClaimCodeLookup_07] FOREIGN KEY ([RegisteredStateId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimVehicle_ClaimCodeLookup_08] FOREIGN KEY ([AntiTheftId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimVehicle_ClaimCodeLookup_10] FOREIGN KEY ([VehicleUseId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId])
) ON [CLAIMSCD];

