CREATE TABLE [dbo].[ClaimPolicyLocation] (
    [ClaimPolicyLocationID]      INT           NOT NULL,
    [LossEventLocationAddressId] INT           NOT NULL,
    [ConstructionTypeDesc]       VARCHAR (40)  NULL,
    [ConstructionYearDt]         CHAR (4)      NULL,
    [RoofTypeId]                 INT           NULL,
    [RoofShapeId]                INT           NULL,
    [RoofPitchId]                INT           NULL,
    [RoofReplacedYearDt]         CHAR (4)      NULL,
    [FireExclusionsDesc]         VARCHAR (25)  NULL,
    [FireExtraBuildingDesc]      VARCHAR (70)  NULL,
    [FO258IndDesc]               CHAR (3)      NULL,
    [FO258PercentDesc]           CHAR (5)      NULL,
    [MortgageeLoanNbr]           CHAR (15)     NULL,
    [AcresNbr]                   INT           NULL,
    [OccupancyDesc]              VARCHAR (30)  NULL,
    [ProtectionClassCd]          VARCHAR (2)   NULL,
    [UnitLocationDesc]           VARCHAR (50)  NULL,
    [LocationNbr]                INT           NULL,
    [NoteDesc]                   VARCHAR (255) NULL,
    [PrimaryLocationInd]         CHAR (1)      NULL,
    [CurrentRecordInd]           BIT           NOT NULL,
    [RetiredInd]                 CHAR (1)      NOT NULL,
    [SourceSystemId]             INT           NOT NULL,
    [SourceSystemCd]             CHAR (2)      NOT NULL,
    [SourceSystemCreatedTmstmp]  DATETIME2 (7) NOT NULL,
    [SourceSystemUserCreatedId]  CHAR (10)     NOT NULL,
    [SourceSystemUpdatedTmstmp]  DATETIME2 (7) NOT NULL,
    [SourceSystemUserUpdatedId]  CHAR (10)     NOT NULL,
    [UserUpdatedId]              CHAR (8)      NOT NULL,
    [UpdatedTmstmp]              DATETIME2 (7) NOT NULL,
    [LastActionCd]               CHAR (1)      NOT NULL,
    CONSTRAINT [PK_ClaimPolicyLocation] PRIMARY KEY CLUSTERED ([ClaimPolicyLocationID] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_ClaimPolicyLocation_LossEventLocationAddress_01] FOREIGN KEY ([LossEventLocationAddressId]) REFERENCES [dbo].[LossEventLocationAddress] ([LossEventLocationAddressId])
) ON [CLAIMSCD];

