CREATE TABLE [dbo].[ClaimFinancialTransaction] (
    [ClaimFinancialTransactionId]          INT             NOT NULL,
    [CostCategoryId]                       INT             NOT NULL,
    [CostTypeId]                           INT             NOT NULL,
    [FinancialTransactionStatusId]         INT             NOT NULL,
    [ApprovalStatusId]                     INT             NULL,
    [TotalTransactionAmt]                  DECIMAL (18, 2) NULL,
    [FinancialBenefitTransactionSubTypeCd] VARCHAR (50)    NOT NULL,
    [TransactionDt]                        DATE            NULL,
    [TransactionSubmitDt]                  DATE            NULL,
    [CommentText]                          VARCHAR (255)   NULL,
    [ApprovalDt]                           DATE            NULL,
    [BatchCycleDt]                         DATE            NULL,
    [RetiredInd]                           CHAR (1)        NOT NULL,
    [CurrentRecordInd]                     BIT             NOT NULL,
    [UpdatedTmstmp]                        DATETIME2 (7)   NOT NULL,
    [UserUpdatedId]                        CHAR (8)        NOT NULL,
    [LastActionCd]                         CHAR (1)        NOT NULL,
    [SourceSystemCd]                       CHAR (2)        NOT NULL,
    [SourceSystemId]                       INT             NOT NULL,
    [ClaimUserCreateTime]                  DATETIME2 (7)   NOT NULL,
    [ClaimUserCreatedId]                   CHAR (8)        NOT NULL,
    [ClaimUserUpdatedId]                   CHAR (8)        NOT NULL,
    [ClaimUpdatedTmstmp]                   DATETIME2 (7)   NOT NULL,
    CONSTRAINT [PK_ClaimFinancialTransaction] PRIMARY KEY CLUSTERED ([ClaimFinancialTransactionId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_ClaimFinancialTransaction_ClaimCodeLookup_01] FOREIGN KEY ([CostCategoryId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimFinancialTransaction_ClaimCodeLookup_02] FOREIGN KEY ([CostTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimFinancialTransaction_ClaimCodeLookup_03] FOREIGN KEY ([FinancialTransactionStatusId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimFinancialTransaction_ClaimCodeLookup_04] FOREIGN KEY ([ApprovalStatusId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId])
) ON [CLAIMSCD];

