CREATE TABLE [dbo].[ClaimCheck] (
    [CheckId]                INT             NOT NULL,
    [ClaimPaymentMethodID]   INT             NULL,
    [EscheatedStatusID]      INT             NULL,
    [BankAccountId]          INT             NULL,
    [PaymentModeId]          INT             NOT NULL,
    [TaxablePayeeId]         INT             NULL,
    [W9CategoryId]           INT             NULL,
    [CheckStatusId]          INT             NOT NULL,
    [DeliveryMethodId]       INT             NULL,
    [StopPmtStatusId]        INT             NULL,
    [CheckTypeId]            INT             NULL,
    [ReportabilityTypeId]    INT             NULL,
    [EscheatContactStatusID] INT             NULL,
    [CheckNbr]               CHAR (10)       NULL,
    [CheckIssueDt]           DATE            NULL,
    [CheckHonorDt]           DATE            NULL,
    [CheckVoidDt]            DATE            NULL,
    [CheckMailToNm]          VARCHAR (250)   NULL,
    [BankCheckHonoredDt]     DATE            NULL,
    [CheckPayableToNm]       VARCHAR (250)   NULL,
    [InvoiceNbr]             VARCHAR (25)    NULL,
    [ServicePeriodStartDt]   DATE            NULL,
    [ServicePeriodEndDt]     DATE            NULL,
    [CheckAmt]               DECIMAL (11, 2) NULL,
    [ScheduledSendDt]        DATE            NULL,
    [UpdatedTmstmp]          DATETIME2 (7)   NOT NULL,
    [UserUpdatedId]          CHAR (8)        NOT NULL,
    [LastActionCd]           CHAR (1)        NOT NULL,
    [SourceSystemCd]         CHAR (2)        NOT NULL,
    [SourceSystemId]         INT             NOT NULL,
    [ClaimUserCreateTime]    DATETIME2 (7)   NOT NULL,
    [ClaimUserCreatedId]     CHAR (8)        NOT NULL,
    [ClaimUserUpdatedId]     CHAR (8)        NOT NULL,
    [ClaimUpdatedTmstmp]     DATETIME2 (7)   NOT NULL,
    [CheckComments]          VARCHAR (50)    NULL,
    [CheckEnteredTime]       DATETIME2 (7)   NULL,
    [ConversionTranDt]       DATE            NULL,
    [CurrentRecordInd]       BIT             NOT NULL,
    [OtherClaimInd]          CHAR (1)        NULL,
    [RecurringCheckInd]      CHAR (1)        NULL,
    [ReplacementCheckInd]    CHAR (1)        NULL,
    [HB191ReplaceCheckInd]   CHAR (1)        NULL,
    [ReplacedCheckNbr]       CHAR (10)       NULL,
    [RetiredInd]             CHAR (1)        NOT NULL,
    [StopInCCOnlyInd]        CHAR (1)        NULL,
    [StopPmtDt]              DATE            NULL,
    [CheckMailingAddress]    VARCHAR (250)   NULL,
    [EscheatedDt]            DATE            NULL,
    [EscheatedAmt]           DECIMAL (18, 2) NULL,
    [EscheatQueueInd]        CHAR (1)        NULL,
    [EscheatLetterSendDt]    DATE            NULL,
    [EscheatLetterExpDt]     DATE            NULL,
    [EQCheckInd]             CHAR (1)        NULL,
    CONSTRAINT [PK_ClaimCheck] PRIMARY KEY CLUSTERED ([CheckId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_ClaimCheck_ClaimCodeLookup_01] FOREIGN KEY ([CheckTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimCheck_ClaimCodeLookup_02] FOREIGN KEY ([DeliveryMethodId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimCheck_ClaimCodeLookup_03] FOREIGN KEY ([ReportabilityTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimCheck_ClaimCodeLookup_04] FOREIGN KEY ([StopPmtStatusId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimCheck_ClaimCodeLookup_05] FOREIGN KEY ([TaxablePayeeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimCheck_ClaimCodeLookup_06] FOREIGN KEY ([PaymentModeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimCheck_ClaimCodeLookup_07] FOREIGN KEY ([W9CategoryId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimCheck_ClaimCodeLookup_08] FOREIGN KEY ([CheckStatusId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimCheck_ClaimCodeLookup_09] FOREIGN KEY ([ClaimPaymentMethodID]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimCheck_ClaimCodeLookup_10] FOREIGN KEY ([EscheatContactStatusID]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimCheck_ClaimCodeLookup_11] FOREIGN KEY ([BankAccountId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_ClaimCheck_ClaimCodeLookup_12] FOREIGN KEY ([EscheatedStatusID]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId])
) ON [CLAIMSCD];

