CREATE TABLE [dbo].[Claim] (
    [ClaimID]                       INT             NOT NULL,
    [ClaimNbr]                      CHAR (10)       NOT NULL,
    [CatastropheId]                 CHAR (10)       NULL,
    [ClaimLossTypeId]               INT             NOT NULL,
    [ClaimLossCauseId]              INT             NULL,
    [LitigationStatusId]            INT             NULL,
    [ClaimStateId]                  INT             NULL,
    [SubrogationStatusId]           INT             NULL,
    [SalvageStatusId]               INT             NULL,
    [CollisionTypeId]               INT             NULL,
    [ExternalAdjusterTypeId]        INT             NULL,
    [ExtAdjusterCompanyId]          INT             NULL,
    [SIUReferReasonId]              INT             NULL,
    [SIUStatusId]                   INT             NULL,
    [ClosedOutComeId]               INT             NULL,
    [InsuredId]                     INT             NULL,
    [ReplacementCostLtrId]          INT             NULL,
    [ClaimDesc]                     VARCHAR (250)   NULL,
    [ClaimLossDt]                   DATE            NULL,
    [ClaimReportDt]                 DATE            NULL,
    [ClaimLossTime]                 TIME (0)        NULL,
    [DtReportedToAgentDt]           DATE            NULL,
    [FatalityCnt]                   INT             NULL,
    [FaultRatingInd]                CHAR (1)        NULL,
    [FatalityInd]                   CHAR (1)        NULL,
    [AutoGlassOnlyInd]              CHAR (1)        NULL,
    [MineSubsidenceInd]             CHAR (1)        NULL,
    [DeerLossInd]                   CHAR (1)        NULL,
    [WeatherRelatedLossInd]         CHAR (1)        NULL,
    [HotLineInd]                    CHAR (1)        NULL,
    [SuspiciousCauseofLossInd]      CHAR (1)        NULL,
    [AgencyHandlingClaimInd]        CHAR (1)        NULL,
    [AgencyHandlingCatInd]          CHAR (1)        NULL,
    [AgencyHandledEligibleInd]      BIT             NULL,
    [CoverageInQuestionInd]         CHAR (1)        NULL,
    [DeductibleStatusInd]           CHAR (1)        NULL,
    [HotlineExternalReferenceNbr]   CHAR (10)       NULL,
    [UpdatedTmstmp]                 DATETIME2 (7)   NOT NULL,
    [UserUpdatedId]                 CHAR (8)        NOT NULL,
    [LastActionCd]                  CHAR (1)        NOT NULL,
    [SourceSystemCd]                CHAR (2)        NOT NULL,
    [SourceSystemId]                INT             NOT NULL,
    [ClaimUserUpdatedId]            CHAR (8)        NOT NULL,
    [ClaimUpdatedTmstmp]            DATETIME2 (7)   NOT NULL,
    [ClaimUserCreateTime]           DATETIME2 (7)   NOT NULL,
    [ClaimUserCreatedId]            CHAR (8)        NOT NULL,
    [CATNotificationSentCd]         CHAR (1)        NULL,
    [DateFirstCATNoticeSentDt]      DATE            NULL,
    [DateSecondCATNoticeSentDt]     DATE            NULL,
    [ExternalAdjusterLastNm]        VARCHAR (35)    NULL,
    [ExternalAdjusterFirstNm]       VARCHAR (35)    NULL,
    [ExtAdjusterAssignedDt]         DATE            NULL,
    [ClaimReopenDt]                 DATE            NULL,
    [ClaimCloseDt]                  DATE            NULL,
    [BackupOverFlowInd]             CHAR (1)        NULL,
    [RefrigProductsInd]             CHAR (1)        NULL,
    [SIUOtherReferReasonDesc]       VARCHAR (30)    NULL,
    [SIUCreateDt]                   DATE            NULL,
    [SIUEstimatedLossAmt]           DECIMAL (18, 2) NULL,
    [SIULossPaidInd]                CHAR (1)        NULL,
    [SIEscalateSIUInd]              CHAR (1)        NULL,
    [SIUSpctDocTxt]                 VARCHAR (2000)  NULL,
    [TotalLossInd]                  CHAR (1)        NULL,
    [ConvertedClaimInd]             CHAR (1)        NULL,
    [HVACInvestigationInd]          CHAR (1)        NULL,
    [RetiredInd]                    CHAR (1)        NOT NULL,
    [CurrentRecordInd]              BIT             NOT NULL,
    [EligibleForArchiveDt]          DATE            NULL,
    [PurgeDt]                       DATE            NULL,
    [AssignmentDt]                  DATE            NULL,
    [ExperinceRateCd]               CHAR (1)        NULL,
    [KFBConversionDt]               DATETIME2 (7)   NULL,
    [ReplacementCostLtrSentDt]      DATE            NULL,
    [TemporaryRepairsInd]           CHAR (1)        NULL,
    [EmergencyServicesContactedInd] CHAR (1)        NULL,
    [FNOLPossibleInjuryInd]         CHAR (1)        NULL,
    [FNOLPossibleInjuryTxt]         TEXT            NULL,
    CONSTRAINT [PK_Claim] PRIMARY KEY CLUSTERED ([ClaimID] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_Claim_Catastrophe_01] FOREIGN KEY ([CatastropheId]) REFERENCES [dbo].[Catastrophe] ([CatastropheNbr]),
    CONSTRAINT [FK_Claim_ClaimCodeLookup_01] FOREIGN KEY ([ClaimLossTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Claim_ClaimCodeLookup_02] FOREIGN KEY ([ClaimLossCauseId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Claim_ClaimCodeLookup_03] FOREIGN KEY ([LitigationStatusId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Claim_ClaimCodeLookup_04] FOREIGN KEY ([CollisionTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Claim_ClaimCodeLookup_05] FOREIGN KEY ([ClaimStateId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Claim_ClaimCodeLookup_06] FOREIGN KEY ([SubrogationStatusId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Claim_ClaimCodeLookup_07] FOREIGN KEY ([SalvageStatusId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Claim_ClaimCodeLookup_08] FOREIGN KEY ([ExternalAdjusterTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Claim_ClaimCodeLookup_09] FOREIGN KEY ([ExtAdjusterCompanyId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Claim_ClaimCodeLookup_10] FOREIGN KEY ([SIUReferReasonId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Claim_ClaimCodeLookup_11] FOREIGN KEY ([SIUStatusId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Claim_ClaimCodeLookup_12] FOREIGN KEY ([ClosedOutComeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Claim_ClaimCodeLookup_14] FOREIGN KEY ([ReplacementCostLtrId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Claim_Party_01] FOREIGN KEY ([InsuredId]) REFERENCES [dbo].[Party] ([PartyId])
) ON [CLAIMSCD] TEXTIMAGE_ON [CLAIMSCD];


GO
CREATE NONCLUSTERED INDEX [IX_Claim_01]
    ON [dbo].[Claim]([ClaimNbr] ASC)
    ON [CLAIMSCI];

