CREATE TABLE [dbo].[CommercialIMUnitEndorsement] (
    [EndorsementNbr]                         CHAR (10)      NOT NULL,
    [PolicyId]                               INT            NOT NULL,
    [EndorsementId]                          INT            NOT NULL,
    [PolicyNbr]                              VARCHAR (16)   NOT NULL,
    [IMPartCoverageTypeCd]                   VARCHAR (50)   NOT NULL,
    [CashUnitNbr]                            CHAR (3)       NULL,
    [EndorsementPremiumAmt]                  DECIMAL (9, 2) NULL,
    [UnitNbr]                                INT            NULL,
    [EndorsementLimitCd]                     CHAR (3)       NULL,
    [EndorsementLimitAmt]                    DECIMAL (9)    NULL,
    [InlandMarineClassCd]                    CHAR (7)       NOT NULL,
    [RiskTypeCd]                             CHAR (10)      NULL,
    [MaximumIndividualLimitAmt]              DECIMAL (9)    NULL,
    [PerEmployeeLimitAmt]                    DECIMAL (9)    NULL,
    [PerOneLossLimitAmt]                     DECIMAL (9)    NULL,
    [PerDayLimitAmt]                         DECIMAL (9)    NULL,
    [CoveredPropertiesEachOccuranceLimitAmt] DECIMAL (9)    NULL,
    [EachVehicleLimitAmt]                    DECIMAL (9)    NULL,
    [FungiIncreasedLimitAmt]                 DECIMAL (9)    NULL,
    [PropertyLimitAmt]                       DECIMAL (9)    NULL,
    [CreatedTmstmp]                          DATETIME       NOT NULL,
    [UserCreatedId]                          CHAR (8)       NOT NULL,
    [UpdatedTmstmp]                          DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]                          CHAR (8)       NOT NULL,
    [LastActionCd]                           CHAR (1)       NOT NULL,
    [SourceSystemCd]                         CHAR (2)       NOT NULL,
    CONSTRAINT [PK_CommercialIMUnitEndorsement] PRIMARY KEY CLUSTERED ([EndorsementNbr] ASC, [EndorsementId] ASC, [PolicyId] ASC, [IMPartCoverageTypeCd] ASC) ON [POLICYCD],
    CONSTRAINT [FK_CommercialIMUnitEndorsement_CommercialIM_01] FOREIGN KEY ([PolicyId], [IMPartCoverageTypeCd]) REFERENCES [dbo].[CommercialIM] ([PolicyId], [IMPartCoverageTypeCd]),
    CONSTRAINT [FK_CommercialIMUnitEndorsement_EndorsementIdentifier_01] FOREIGN KEY ([EndorsementId]) REFERENCES [dbo].[Endorsements] ([EndorsementId])
) ON [POLICYCD];

