CREATE TABLE [dbo].[CommercialGLQuoteCoverage] (
    [QuoteNbr]                                          VARCHAR (16)   NOT NULL,
    [EachIncidentCoverageLimitAmt]                      DECIMAL (9)    NULL,
    [EachIncidentCoveragePremiumAmt]                    DECIMAL (9, 2) NULL,
    [TotalCoverageLimitAmt]                             DECIMAL (9)    NOT NULL,
    [TotalCoveragePremiumAmt]                           DECIMAL (9, 2) NOT NULL,
    [OperationsTotalLimitAmt]                           DECIMAL (9)    NULL,
    [OperationsTotalPremiumAmt]                         DECIMAL (9, 2) NULL,
    [PremisesDamageLimitAmt]                            DECIMAL (9)    NULL,
    [PremisesDamagePremiumAmt]                          DECIMAL (9, 2) NULL,
    [PerPersonMedicalLimitAmt]                          DECIMAL (9)    NULL,
    [PerPersonMedicalPremiumAmt]                        DECIMAL (9, 2) NULL,
    [InjuryLimitAmt]                                    DECIMAL (9)    NULL,
    [InjuryPremiumAmt]                                  DECIMAL (9, 2) NULL,
    [BusinessIncomeAddlitionalLimitAmt]                 DECIMAL (9)    NULL,
    [BusinessIncomeTotalLimitAmt]                       DECIMAL (9)    NULL,
    [AccountReceivablesAdditionalLimitAmt]              DECIMAL (9)    NULL,
    [AccountReceivablesPremisesLimitAmt]                DECIMAL (9)    NULL,
    [AccountReceivablesOffPremisesLimitAmt]             DECIMAL (9)    NULL,
    [AccountReceivablesPremiumAmt]                      DECIMAL (9, 2) NULL,
    [ValuablePapersAdditionalLimitAmt]                  DECIMAL (9)    NULL,
    [ValuablePapersOffPremisesLimitAmt]                 DECIMAL (9)    NULL,
    [ValuablePapersPremisesLimitAmt]                    DECIMAL (9)    NULL,
    [ValuablePapersPremiumAmt]                          DECIMAL (9, 2) NULL,
    [EmployeeDishonestyLimitAmt]                        DECIMAL (9)    NULL,
    [EmployeeDishonestyPremiumAmt]                      DECIMAL (9, 2) NULL,
    [DishonestEmployeeCnt]                              INT            NULL,
    [BusinessIncomeOrdinaryPayrollExpenseDayCnt]        INT            NULL,
    [BusinessIncomeOrdinaryPayrollExpenseDayPremiumAmt] DECIMAL (9, 2) NULL,
    [ExtendedBusinessIncomeIndemnityDayCnt]             INT            NULL,
    [ExtendedBusinessIncomeIndemnityPremiumAmt]         DECIMAL (9, 2) NULL,
    [MoneySecuritiesOffPremisesLimitAmt]                DECIMAL (9)    NULL,
    [MoneySecuritiesPremisesLimitAmt]                   DECIMAL (9)    NULL,
    [MoneySecuritiesPremiumAmt]                         DECIMAL (9, 2) NULL,
    [ElectronicDataAdditionalLimitAmt]                  DECIMAL (9)    NULL,
    [ElectronicDataLimitAmt]                            DECIMAL (9)    NULL,
    [ElectronicDataPremiumAmt]                          DECIMAL (9, 2) NULL,
    [ComputerInterruptAdditionalLimitAmt]               DECIMAL (9)    NULL,
    [ComputerInterruptLimitAmt]                         DECIMAL (9)    NULL,
    [ComputerInterruptPremiumAmt]                       DECIMAL (9, 2) NULL,
    [CombinaitonEmployeeForgeryAlterationLimitAmt]      DECIMAL (9)    NULL,
    [CombinaitonEmployeeForgeryAlterationPremiumAmt]    DECIMAL (9, 2) NULL,
    [CombinaitonForgeryAlterationEmployeeCnt]           INT            NULL,
    [FireDepartmentServiceChargeLmtAmt]                 DECIMAL (9)    NULL,
    [FireDepartmentServiceChargePremAmt]                DECIMAL (9, 2) NULL,
    [CreatedTmstmp]                                     DATETIME       NOT NULL,
    [UserCreatedId]                                     CHAR (8)       NOT NULL,
    [UpdatedTmstmp]                                     DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]                                     CHAR (8)       NOT NULL,
    [LastActionCd]                                      CHAR (1)       NOT NULL,
    [SourceSystemCd]                                    CHAR (2)       NOT NULL,
    CONSTRAINT [PK_CommercialGLQuoteCoverage] PRIMARY KEY CLUSTERED ([QuoteNbr] ASC) ON [POLICYCD],
    CONSTRAINT [FK_CommercialGLQuoteCoverage_CommercialGLPolicyQuote_01] FOREIGN KEY ([QuoteNbr]) REFERENCES [dbo].[CommercialGLQuote] ([QuoteNbr])
) ON [POLICYCD];

