CREATE TABLE [dbo].[CommercialBuildingUnit] (
    [PolicyId]                  INT             NOT NULL,
    [UnitNbr]                   INT             NOT NULL,
    [LocationID]                BIGINT          NULL,
    [PolicyNbr]                 VARCHAR (16)    NOT NULL,
    [ProgramCd]                 CHAR (1)        NULL,
    [CashUnitNbr]               CHAR (3)        NULL,
    [LocationNameDesc]          VARCHAR (255)   NULL,
    [TotalAreaNbr]              INT             NULL,
    [BuildingDesc]              VARCHAR (255)   NULL,
    [BoilerInsuredElsewhereInd] CHAR (1)        NULL,
    [BoilerOnPremisesInd]       CHAR (1)        NULL,
    [BurglarySafegaurdDesc]     VARCHAR (255)   NULL,
    [BasementInd]               CHAR (1)        NULL,
    [RateTypeCd]                CHAR (2)        NULL,
    [ConstructionTypeCd]        CHAR (1)        NULL,
    [ConstructionTypeDesc]      CHAR (50)       NULL,
    [DistanceFromFireStationCd] CHAR (2)        NULL,
    [ConstructionYearDt]        CHAR (4)        NULL,
    [DistanceFromHydrantCd]     CHAR (2)        NULL,
    [SwimmingPoolInd]           CHAR (1)        NULL,
    [DivingBoardInd]            CHAR (1)        NULL,
    [EQAddDt]                   DATE            NULL,
    [EQRemoveDt]                DATE            NULL,
    [ExitsCnt]                  INT             NULL,
    [FencedOrGatedIndicatorInd] CHAR (1)        NULL,
    [FireProtectionAreaNm]      VARCHAR (300)   NULL,
    [FrontExposureDesc]         VARCHAR (255)   NULL,
    [LeftExposureDesc]          VARCHAR (255)   NULL,
    [RearExposureDesc]          VARCHAR (255)   NULL,
    [RightExposureDesc]         VARCHAR (255)   NULL,
    [HeatUpgradeYearDt]         CHAR (4)        NULL,
    [PlummingUpgradeYearDt]     CHAR (4)        NULL,
    [OccupancyTypeCd]           CHAR (1)        NULL,
    [PropertyClassCd]           CHAR (7)        NULL,
    [PurchaseDt]                DATE            NOT NULL,
    [PurchasePriceAmt]          DECIMAL (10, 2) NULL,
    [ProtectionClassCd]         VARCHAR (2)     NULL,
    [RoofTypeCd]                CHAR (2)        NOT NULL,
    [RoofConstructionYearDt]    CHAR (4)        NULL,
    [RoofUpgradeYearDt]         CHAR (4)        NULL,
    [SmokeDetectorCnt]          INT             NULL,
    [SprinkleredPct]            DECIMAL (5, 2)  NULL,
    [RentedPct]                 DECIMAL (5, 2)  NULL,
    [VacantPercentRangeNbr]     VARCHAR (50)    NULL,
    [WiringConditionDesc]       VARCHAR (255)   NULL,
    [WiringTypeDesc]            VARCHAR (255)   NULL,
    [WiringUpgradeYearDt]       CHAR (4)        NULL,
    [FireProtectionClassCd]     CHAR (10)       NULL,
    [AllinesItemNbr]            CHAR (3)        NULL,
    [RateClassCd]               CHAR (1)        NULL,
    [SurchargeExemptStatusCd]   CHAR (1)        NULL,
    [EarthquakeCoverageCd]      CHAR (1)        NULL,
    [EarthquakeConstructionCd]  CHAR (1)        NULL,
    [MineSubsidenceInd]         CHAR (1)        NULL,
    [ProductsCompletedInd]      CHAR (1)        NULL,
    [MinimumPremiumInd]         CHAR (1)        NULL,
    [CoinsurancePercentCd]      CHAR (1)        NULL,
    [AllinesLocationCountyNbr]  CHAR (3)        NULL,
    [TerritoryCd]               CHAR (1)        NULL,
    [PropertyClassDesc]         VARCHAR (255)   NULL,
    [CauseOfLossDesc]           VARCHAR (255)   NULL,
    [AutomaticSprinklerInd]     CHAR (1)        NULL,
    [FloorCnt]                  INT             NULL,
    [ExtinguisherCnt]           INT             NULL,
    [AlarmInd]                  CHAR (1)        NULL,
    [AlarmTypeDesc]             VARCHAR (200)   NULL,
    [SwimmingPoolCnt]           INT             NULL,
    [TanningBedCnt]             INT             NULL,
    [PrimaryHeatingDesc]        VARCHAR (50)    NULL,
    [CreatedTmstmp]             DATETIME        NOT NULL,
    [UserCreatedId]             CHAR (8)        NOT NULL,
    [UpdatedTmstmp]             DATETIME2 (7)   NOT NULL,
    [UserUpdatedId]             CHAR (8)        NOT NULL,
    [LastActionCd]              CHAR (1)        NOT NULL,
    [SourceSystemCd]            CHAR (2)        NOT NULL,
    CONSTRAINT [PK_CommercialBuildingUnit] PRIMARY KEY CLUSTERED ([PolicyId] ASC, [UnitNbr] ASC) ON [POLICYCD],
    CONSTRAINT [FK_CommercialBuildingUnit_CommercialPolicy_01] FOREIGN KEY ([PolicyId]) REFERENCES [dbo].[CommercialPolicy] ([PolicyId]),
    CONSTRAINT [FK_CommercialBuildingUnit_Location_01] FOREIGN KEY ([LocationID]) REFERENCES [dbo].[Location] ([LocationID])
) ON [POLICYCD];


GO
CREATE NONCLUSTERED INDEX [IX_CommercialBuildingUnit_01]
    ON [dbo].[CommercialBuildingUnit]([PolicyId] ASC)
    ON [POLICYCI];

