CREATE TABLE [dbo].[CommercialPolicy] (
    [PolicyId]                    INT             NOT NULL,
    [PolicyNbr]                   VARCHAR (16)    NOT NULL,
    [CoinsurancePercentCd]        CHAR (1)        NULL,
    [ConstructionTypeCd]          CHAR (1)        NULL,
    [ConstructionYearDt]          CHAR (4)        NULL,
    [CrimeCoverageOptionCd]       CHAR (1)        NULL,
    [InflationGuardCd]            VARCHAR (1)     NULL,
    [ProtectionClassCd]           VARCHAR (2)     NULL,
    [SprinklerSystemInd]          CHAR (1)        NULL,
    [RateClassCd]                 CHAR (5)        NULL,
    [ProgramCd]                   CHAR (1)        NULL,
    [IMMinimumPremiumAmt]         DECIMAL (9, 2)  NULL,
    [GLMinimumPremiumAmt]         DECIMAL (9, 2)  NULL,
    [CommercialMinimumPremiumAmt] DECIMAL (9, 2)  NULL,
    [AuditDoneInd]                CHAR (1)        NULL,
    [AuditSendCd]                 CHAR (1)        NULL,
    [TerritoryCd]                 CHAR (1)        NULL,
    [ComputerRatedLevelCd]        CHAR (1)        NULL,
    [PolicyTypeCd]                CHAR (1)        NULL,
    [IRPMPct]                     INT             NULL,
    [LocationCountyNbr]           CHAR (3)        NULL,
    [InspectionInd]               CHAR (1)        NULL,
    [ExtraUnitsInd]               CHAR (1)        NULL,
    [ExtraInlandMarinesInd]       CHAR (1)        NULL,
    [ExtraMortgageesInd]          CHAR (1)        NULL,
    [BuildersRiskInd]             CHAR (1)        NULL,
    [PolicyLimitCd]               CHAR (1)        NULL,
    [EntityTypeCd]                CHAR (1)        NULL,
    [CrimeCoverageInd]            CHAR (1)        NULL,
    [ClassRiskCd]                 VARCHAR (22)    NULL,
    [CPSelectInd]                 CHAR (1)        NOT NULL,
    [GLSelectInd]                 CHAR (1)        NOT NULL,
    [IMSelectInd]                 CHAR (1)        NOT NULL,
    [DeductibleAmt]               DECIMAL (18, 2) NULL,
    [EmployeeCnt]                 INT             NULL,
    [LegalEntityTypeDesc]         VARCHAR (50)    NULL,
    [ReinsuranceCategoryCd]       CHAR (2)        NULL,
    [SurchargeExemptInd]          CHAR (1)        NULL,
    [VolunteerCnt]                INT             NULL,
    [VolunteerEmployeeInd]        CHAR (1)        NULL,
    [TerrorismCoveredInd]         CHAR (1)        NULL,
    [EQAddDt]                     DATE            NULL,
    [EQRemoveDt]                  DATE            NULL,
    [TerrorismRenewalPremAmt]     DECIMAL (9, 2)  NULL,
    [IRPMDesc]                    VARCHAR (255)   NULL,
    [TerrorismCoveragePremiumAmt] DECIMAL (9, 2)  NULL,
    [BOPSelectInd]                CHAR (1)        NOT NULL,
    [BOPMinimumPremiumAmt]        DECIMAL (9, 2)  NULL,
    [IRPMConversionNbr]           INT             NULL,
    [UpdatedTmstmp]               DATETIME2 (7)   NOT NULL,
    [UserUpdatedId]               CHAR (8)        NOT NULL,
    [LastActionCd]                CHAR (1)        NOT NULL,
    [SourceSystemCd]              CHAR (2)        NOT NULL,
    CONSTRAINT [PK_CommercialPolicy] PRIMARY KEY CLUSTERED ([PolicyId] ASC) ON [POLICYCD],
    CONSTRAINT [FK_CommercialPolicy_Policy_01] FOREIGN KEY ([PolicyId]) REFERENCES [dbo].[Policy] ([PolicyId])
) ON [POLICYCD];

