CREATE TABLE [dbo].[DriverightMobileHistory] (
    [DriveRightMobileHistoryId] INT            NOT NULL,
    [PolicyId]                  INT            NULL,
    [UnitNbr]                   INT            NULL,
    [PolicyPartyRelationId]     INT            NULL,
    [PolicyNbr]                 VARCHAR (16)   NOT NULL,
    [PremiumScoreModelVerTxt]   VARCHAR (20)   NULL,
    [ScoreNbr]                  DECIMAL (8, 4) NULL,
    [DriverNbr]                 INT            NOT NULL,
    [PremiumScoreLambdaNbr]     DECIMAL (8, 6) NULL,
    [ScoreDt]                   DATETIME2 (7)  NULL,
    [ScoreAccelNbr]             DECIMAL (8, 4) NULL,
    [DistanceNbr]               DECIMAL (8, 2) NULL,
    [DurationNbr]               INT            NULL,
    [TripsCnt]                  INT            NULL,
    [PremiumScoreEndDt]         DATE           NULL,
    [PremiumScoreStartDt]       DATE           NULL,
    [PremiumScoreDistanceKmCnt] DECIMAL (8, 2) NULL,
    [ScoreTurnPointsNbr]        DECIMAL (8, 4) NULL,
    [ScoreSpeedingPointsNbr]    DECIMAL (8, 4) NULL,
    [ScoreTurnNbr]              DECIMAL (8, 4) NULL,
    [ScoreSpeedingNbr]          DECIMAL (8, 4) NULL,
    [NightDistanceNbr]          DECIMAL (8, 2) NULL,
    [ScoreBrakePointsNbr]       DECIMAL (8, 4) NULL,
    [PremiumScoreNbr]           DECIMAL (8, 4) NULL,
    [ScoreBrakeNbr]             DECIMAL (8, 4) NULL,
    [PremiumScoreTripsCnt]      INT            NULL,
    [PremiumScoreModelNameTxt]  VARCHAR (20)   NULL,
    [ScoreDistractionPointsNbr] DECIMAL (8, 4) NULL,
    [ScoreDistractionNbr]       DECIMAL (8, 4) NULL,
    [WeightedScoreInd]          CHAR (1)       NULL,
    [UpdatedTmstmp]             DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]             CHAR (8)       NOT NULL,
    [LastActionCd]              CHAR (1)       NOT NULL,
    [SourceSystemCd]            CHAR (2)       NOT NULL,
    CONSTRAINT [PK_DriverightMobileHistory] PRIMARY KEY CLUSTERED ([DriveRightMobileHistoryId] ASC) ON [POLICYCD],
    CONSTRAINT [FK_DriveRightMobileHistory_Driver_01] FOREIGN KEY ([PolicyPartyRelationId], [PolicyId], [UnitNbr]) REFERENCES [dbo].[Driver] ([PolicyPartyRelationId], [PolicyId], [UnitNbr])
) ON [POLICYCD];

