CREATE TABLE [dbo].[DriveRightQuoteMobileHistory] (
    [DriveRightQuoteMobileHistoryId] INT            NOT NULL,
    [UnitNbr]                        INT            NULL,
    [QuotePartyRelationId]           INT            NULL,
    [QuoteNbr]                       VARCHAR (16)   NULL,
    [PremiumScoreModelVerTxt]        VARCHAR (20)   NULL,
    [ScoreNbr]                       DECIMAL (8, 4) NULL,
    [DriverNbr]                      INT            NULL,
    [PremiumScoreLambdaNbr]          DECIMAL (8, 6) NULL,
    [ScoreDt]                        DATETIME2 (7)  NULL,
    [ScoreAccelNbr]                  DECIMAL (8, 4) NULL,
    [DistanceNbr]                    DECIMAL (8, 2) NULL,
    [DurationNbr]                    INT            NULL,
    [TripsCnt]                       INT            NULL,
    [PremiumScoreEndDate]            DATE           NULL,
    [PremiumScoreStartDt]            DATE           NULL,
    [PremiumScoreDistanceKmCnt]      DECIMAL (8, 2) NULL,
    [ScoreTurnPointsNbr]             DECIMAL (8, 4) NULL,
    [ScoreSpeedingPointsNbr]         DECIMAL (8, 4) NULL,
    [ScoreTurnNbr]                   DECIMAL (8, 4) NULL,
    [ScoreSpeedingNbr]               DECIMAL (8, 4) NULL,
    [NightDistanceNbr]               DECIMAL (8, 2) NULL,
    [ScoreBrakePointsNbr]            DECIMAL (8, 4) NULL,
    [PremiumScoreNbr]                DECIMAL (8, 4) NULL,
    [ScoreBrakeNbr]                  DECIMAL (8, 4) NULL,
    [PremiumScoreTripsCnt]           INT            NULL,
    [PremiumScoreModelNameTxt]       VARCHAR (20)   NULL,
    [ScoreDistractionPointsNbr]      DECIMAL (8, 4) NULL,
    [ScoreDistractionNbr]            DECIMAL (8, 4) NULL,
    [WeightedScoreInd]               CHAR (1)       NULL,
    [UpdatedTmstmp]                  DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]                  CHAR (8)       NOT NULL,
    [LastActionCd]                   CHAR (1)       NOT NULL,
    [SourceSystemCd]                 CHAR (2)       NOT NULL,
    CONSTRAINT [PK_DriveRightQuoteMobilityHistory] PRIMARY KEY CLUSTERED ([DriveRightQuoteMobileHistoryId] ASC) ON [POLICYCD],
    CONSTRAINT [FK_DriveRightQuoteMobileHistory_AutoQuoteDriver_01] FOREIGN KEY ([QuoteNbr], [UnitNbr], [QuotePartyRelationId]) REFERENCES [dbo].[AutoQuoteDriver] ([QuoteNbr], [UnitNbr], [QuotePartyRelationId])
) ON [POLICYCD];

