CREATE TABLE [dbo].[FarmUnitDwelling] (
    [PolicyId]                       INT             NOT NULL,
    [UnitNbr]                        INT             NOT NULL,
    [UnitTypeCd]                     CHAR (1)        NOT NULL,
    [LocationID]                     BIGINT          NULL,
    [PolicyNbr]                      VARCHAR (16)    NOT NULL,
    [SourceSystemDisplayUnitNbr]     INT             NULL,
    [CashUnitNbr]                    CHAR (3)        NULL,
    [DwellingTypeDesc]               VARCHAR (50)    NULL,
    [DistanceFromFireStationCd]      CHAR (2)        NULL,
    [DistanceFromHydrantCd]          CHAR (2)        NULL,
    [FireProtectionAreaNm]           VARCHAR (300)   NULL,
    [ProtectionClassCd]              VARCHAR (2)     NULL,
    [InflationGuardCd]               VARCHAR (1)     NULL,
    [RateClassCd]                    CHAR (2)        NULL,
    [PurchaseDt]                     DATE            NULL,
    [PurchasePriceAmt]               DECIMAL (10, 2) NULL,
    [OccupancyTypeCd]                CHAR (1)        NULL,
    [OtherInsurerInd]                CHAR (1)        NULL,
    [OtherInsuranceExplainationDesc] VARCHAR (255)   NULL,
    [PreviousDwellingInsuranceInd]   CHAR (1)        NULL,
    [PreviousDewllingInsuranceDesc]  VARCHAR (255)   NULL,
    [ConstructionTypeCd]             CHAR (1)        NULL,
    [ConstructionYearDt]             CHAR (4)        NULL,
    [ConstructionTypeDesc]           CHAR (50)       NULL,
    [HeatingUpgradeYearDt]           CHAR (4)        NULL,
    [PlumbingUpgradeYearDt]          CHAR (4)        NULL,
    [WiringUpgradeYearDt]            CHAR (4)        NULL,
    [PrimaryHeatingDesc]             VARCHAR (50)    NULL,
    [PrimaryHeatingOtherDesc]        VARCHAR (50)    NULL,
    [SprinklerSystemTypeDesc]        VARCHAR (50)    NULL,
    [MineSubsidenceCoverageCd]       CHAR (1)        NULL,
    [MainDwellingOccupierDesc]       VARCHAR (255)   NULL,
    [SwimmingPoolInd]                CHAR (1)        NULL,
    [FencedOrGatedInd]               CHAR (1)        NULL,
    [DivingBoardInd]                 CHAR (1)        NULL,
    [FireExtinguishersInd]           CHAR (1)        NULL,
    [FireAlarmInd]                   CHAR (1)        NULL,
    [SmokeAlarmInd]                  CHAR (1)        NULL,
    [DeadboltInd]                    CHAR (1)        NULL,
    [ContractorBuiltInd]             CHAR (1)        NULL,
    [EQAddDt]                        DATE            NULL,
    [EQRemoveDt]                     DATE            NULL,
    [BurglurAlarmInd]                CHAR (1)        NULL,
    [BurglurAlarmTypeDesc]           VARCHAR (255)   NULL,
    [FireAlarmTypeDesc]              VARCHAR (255)   NULL,
    [LengthNbr]                      DECIMAL (5)     NULL,
    [WidthNbr]                       DECIMAL (5)     NULL,
    [ManufacturerNm]                 VARCHAR (255)   NULL,
    [SerialNbr]                      CHAR (20)       NULL,
    [RateClassDesc]                  VARCHAR (255)   NULL,
    [MineSubsidancePremiumAmt]       DECIMAL (9, 2)  NULL,
    [CreatedTmstmp]                  DATETIME        NOT NULL,
    [UserCreatedId]                  CHAR (8)        NOT NULL,
    [UpdatedTmstmp]                  DATETIME2 (7)   NOT NULL,
    [UserUpdatedId]                  CHAR (8)        NOT NULL,
    [LastActionCd]                   CHAR (1)        NOT NULL,
    [SourceSystemCd]                 CHAR (2)        NOT NULL,
    CONSTRAINT [PK_FarmUnitDwelling] PRIMARY KEY CLUSTERED ([PolicyId] ASC, [UnitNbr] ASC, [UnitTypeCd] ASC) ON [POLICYCD],
    CONSTRAINT [FK_FarmUnitDwelling_FarmUnit_01] FOREIGN KEY ([PolicyId], [UnitNbr], [UnitTypeCd]) REFERENCES [dbo].[FarmUnit] ([PolicyId], [UnitNbr], [UnitTypeCd]),
    CONSTRAINT [FK_FarmUnitDwelling_Location_01] FOREIGN KEY ([LocationID]) REFERENCES [dbo].[Location] ([LocationID])
) ON [POLICYCD];


GO
CREATE NONCLUSTERED INDEX [IX_FarmUnitDwelling_01]
    ON [dbo].[FarmUnitDwelling]([PolicyId] ASC)
    ON [POLICYCI];

