CREATE TABLE [dbo].[FarmQuoteUnitEquipment] (
    [QuoteNbr]                    VARCHAR (16)   NOT NULL,
    [UnitNbr]                     INT            NOT NULL,
    [UnitTypeCd]                  CHAR (1)       NOT NULL,
    [LocationID]                  BIGINT         NULL,
    [ItemCoverageLimitAmt]        DECIMAL (9)    NULL,
    [ItemCoveragePremiumGrossAmt] DECIMAL (9, 2) NULL,
    [ManufacturerNm]              VARCHAR (50)   NULL,
    [ManufacturingYearDt]         CHAR (4)       NULL,
    [ModelNm]                     VARCHAR (100)  NULL,
    [SerialNbr]                   CHAR (20)      NULL,
    [AdditionalInsuredPersonsNm]  VARCHAR (50)   NULL,
    [LivestockDesc]               VARCHAR (100)  NULL,
    [LivestockRegistrationNbr]    CHAR (20)      NULL,
    [UnitCnt]                     INT            NULL,
    [UnitAmt]                     DECIMAL (9, 2) NULL,
    [EquipmentUseDesc]            VARCHAR (255)  NULL,
    [EquipmentDesc]               VARCHAR (255)  NULL,
    [BulldozerOrBackhoeInd]       CHAR (1)       NULL,
    [LeaseInd]                    CHAR (1)       NULL,
    [EquipmentCategoryDesc]       VARCHAR (255)  NULL,
    [LiabilityInd]                CHAR (1)       NULL,
    [CreatedTmstmp]               DATETIME       NOT NULL,
    [UserCreatedId]               CHAR (8)       NOT NULL,
    [UpdatedTmstmp]               DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]               CHAR (8)       NOT NULL,
    [LastActionCd]                CHAR (1)       NOT NULL,
    [SourceSystemCd]              CHAR (2)       NOT NULL,
    CONSTRAINT [PK_FarmQuoteUnitEquipment] PRIMARY KEY CLUSTERED ([UnitNbr] ASC, [UnitTypeCd] ASC, [QuoteNbr] ASC) ON [POLICYCD],
    CONSTRAINT [FK_FarmUnitQuoteEquipment_FarmUnitQuote_01] FOREIGN KEY ([UnitNbr], [UnitTypeCd], [QuoteNbr]) REFERENCES [dbo].[FarmQuoteUnit] ([UnitNbr], [UnitTypeCd], [QuoteNbr]),
    CONSTRAINT [FK_FarmUnitQuoteEquipment_Location_01] FOREIGN KEY ([LocationID]) REFERENCES [dbo].[Location] ([LocationID])
) ON [POLICYCD];

