CREATE TABLE [dbo].[FarmQuoteUnitOutBuilding] (
    [QuoteNbr]                      VARCHAR (16)   NOT NULL,
    [UnitNbr]                       INT            NOT NULL,
    [UnitTypeCd]                    CHAR (1)       NOT NULL,
    [OutBuildingNbr]                INT            NOT NULL,
    [LocationID]                    BIGINT         NULL,
    [WithLivingSpaceInd]            CHAR (1)       NULL,
    [WithGarageInd]                 CHAR (1)       NULL,
    [WithEquipmentInd]              CHAR (1)       NULL,
    [WithStorageInd]                CHAR (1)       NULL,
    [WithHeatInd]                   CHAR (1)       NULL,
    [WithShopInd]                   CHAR (1)       NULL,
    [WithBarnInd]                   CHAR (1)       NULL,
    [WithStrippingRoomInd]          CHAR (1)       NULL,
    [EQAddDt]                       DATE           NULL,
    [EQRemoveDt]                    DATE           NULL,
    [FarmBuildingTypeCd]            CHAR (1)       NULL,
    [FarmBuildingClassCd]           CHAR (2)       NULL,
    [MineSubsidenceInd]             CHAR (1)       NULL,
    [ConstructionTypeCd]            CHAR (2)       NULL,
    [ConstructionYearDt]            CHAR (4)       NULL,
    [BuildingTypeDesc]              VARCHAR (255)  NULL,
    [FO258PercentCd]                CHAR (1)       NULL,
    [OutBuildingCoverageLimitAmt]   DECIMAL (9)    NULL,
    [OutBuildingCoveragePremiumAmt] DECIMAL (9, 2) NULL,
    [AdditionalInsuredPersonsNm]    VARCHAR (50)   NULL,
    [OutBuildingDesc]               VARCHAR (250)  NULL,
    [ConstructionTypeDesc]          CHAR (50)      NULL,
    [PrimaryHeatingDesc]            VARCHAR (50)   NULL,
    [PrimaryHeatingOtherDesc]       VARCHAR (50)   NULL,
    [LeaseInd]                      CHAR (1)       NULL,
    [LengthNbr]                     DECIMAL (5)    NULL,
    [WidthNbr]                      DECIMAL (5)    NULL,
    [AdditionalDesc]                VARCHAR (255)  NULL,
    [RoofConstructionYearDt]        CHAR (4)       NULL,
    [ResidenceUsedAsDesc]           VARCHAR (255)  NULL,
    [ExpeditorDesc]                 VARCHAR (255)  NULL,
    [ManufacturerNm]                VARCHAR (50)   NULL,
    [ModelNm]                       VARCHAR (100)  NULL,
    [SerialNbr]                     CHAR (20)      NULL,
    [LiabilityInd]                  CHAR (1)       NULL,
    [FoundationDesc]                VARCHAR (255)  NULL,
    [MineSubsidancePremiumAmt]      DECIMAL (9, 2) NULL,
    [UpdatedTmstmp]                 DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]                 CHAR (8)       NOT NULL,
    [LastActionCd]                  CHAR (1)       NOT NULL,
    [SourceSystemCd]                CHAR (2)       NOT NULL,
    CONSTRAINT [PK_FarmQuoteUnitOutBuilding] PRIMARY KEY CLUSTERED ([UnitNbr] ASC, [OutBuildingNbr] ASC, [UnitTypeCd] ASC, [QuoteNbr] ASC) ON [POLICYCD],
    CONSTRAINT [FK_FarmQuoteOutBuilding_FarmUnitQuote_01] FOREIGN KEY ([UnitNbr], [UnitTypeCd], [QuoteNbr]) REFERENCES [dbo].[FarmQuoteUnit] ([UnitNbr], [UnitTypeCd], [QuoteNbr]),
    CONSTRAINT [FK_FarmUnitQuoteOutBuilding_Location_01] FOREIGN KEY ([LocationID]) REFERENCES [dbo].[Location] ([LocationID])
) ON [POLICYCD];

