CREATE TABLE [dbo].[FarmQuoteUnitEndorsementDetail] (
    [QuoteNbr]                    VARCHAR (16)   NOT NULL,
    [UnitNbr]                     INT            NOT NULL,
    [UnitTypeCd]                  CHAR (1)       NOT NULL,
    [EndorsementId]               INT            NOT NULL,
    [ItemNbr]                     CHAR (3)       NOT NULL,
    [ArticleNbr]                  CHAR (3)       NOT NULL,
    [LocationID]                  BIGINT         NULL,
    [EndorsementNbr]              CHAR (10)      NOT NULL,
    [ItemCoverageLimitAmt]        DECIMAL (9)    NULL,
    [ItemCoveragePremiumGrossAmt] DECIMAL (9, 2) NULL,
    [ItemBasicDesc]               VARCHAR (250)  NULL,
    [ItemFreeFormDesc]            TEXT           NULL,
    [ManufacturerNm]              VARCHAR (50)   NULL,
    [ManufacturingYearDt]         CHAR (4)       NULL,
    [ModelNm]                     VARCHAR (100)  NULL,
    [SerialNbr]                   CHAR (20)      NULL,
    [InturruptCnt]                INT            NULL,
    [IncreaseForItemDesc]         CHAR (150)     NULL,
    [LivestockUnitCnt]            INT            NULL,
    [LivestockWeightNbr]          INT            NULL,
    [LivestockTotalValueAmt]      DECIMAL (9)    NULL,
    [LivestockBackupDesc]         VARCHAR (100)  NULL,
    [SignalTypeDesc]              VARCHAR (255)  NULL,
    [MembershipNbr]               CHAR (10)      NULL,
    [PlantCnt]                    INT            NULL,
    [TrayCnt]                     INT            NULL,
    [OutBuildingDesc]             VARCHAR (250)  NULL,
    [DaysNbr]                     INT            NULL,
    [MonthNm]                     CHAR (10)      NULL,
    [DayCnt]                      INT            NULL,
    [NumberPlantsCnt]             INT            NULL,
    [CreatedTmstmp]               DATETIME2 (7)  NOT NULL,
    [UserCreatedId]               CHAR (8)       NOT NULL,
    [UpdatedTmstmp]               DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]               CHAR (8)       NOT NULL,
    [LastActionCd]                CHAR (1)       NOT NULL,
    [SourceSystemCd]              CHAR (2)       NOT NULL,
    CONSTRAINT [PK_FarmQuoteUnitEndorsementDetail] PRIMARY KEY CLUSTERED ([UnitNbr] ASC, [UnitTypeCd] ASC, [QuoteNbr] ASC, [EndorsementId] ASC, [ItemNbr] ASC, [ArticleNbr] ASC),
    CONSTRAINT [FK_FarmUnitQuoteEndorsementDetail_FarmUnitQuoteEndorsement_01] FOREIGN KEY ([UnitNbr], [UnitTypeCd], [QuoteNbr], [EndorsementId]) REFERENCES [dbo].[FarmQuoteUnitEndorsement] ([UnitNbr], [UnitTypeCd], [QuoteNbr], [EndorsementId]),
    CONSTRAINT [FK_FarmUnitQuoteEndorsementDetail_Location_01] FOREIGN KEY ([LocationID]) REFERENCES [dbo].[Location] ([LocationID])
);

