CREATE TABLE [dbo].[FarmQuoteUnitEndorsement] (
    [QuoteNbr]                      VARCHAR (16)   NOT NULL,
    [UnitNbr]                       INT            NOT NULL,
    [UnitTypeCd]                    CHAR (1)       NOT NULL,
    [EndorsementId]                 INT            NOT NULL,
    [EndorsementNbr]                CHAR (10)      NOT NULL,
    [EndorsementLimitCd]            CHAR (3)       NULL,
    [EndorsementLimitAmt]           DECIMAL (9)    NULL,
    [EndorsementPremiumAmt]         DECIMAL (9, 2) NULL,
    [EndorsementProratedPremiumAmt] DECIMAL (9, 2) NULL,
    [EndorsemenrtDeductiblePct]     DECIMAL (5, 2) NULL,
    [ChildrenCnt]                   CHAR (3)       NULL,
    [ReplacementPct]                DECIMAL (5, 2) NULL,
    [VacancyStartingDt]             DATE           NULL,
    [VacancyEndingDt]               DATE           NULL,
    [CoverageDesc]                  VARCHAR (250)  NULL,
    [ConstructionTypeDesc]          CHAR (50)      NULL,
    [DiscountPct]                   DECIMAL (5, 2) NULL,
    [FarmingOperationsDesc]         VARCHAR (255)  NULL,
    [MonthNbr]                      SMALLINT       NULL,
    [IncidentalCoverageDesc]        VARCHAR (250)  NULL,
    [IncreaseContentsCoverageInd]   CHAR (1)       NULL,
    [VaneerExclusionInd]            CHAR (1)       NULL,
    [CreatedTmstmp]                 DATETIME       NOT NULL,
    [UserCreatedId]                 CHAR (8)       NOT NULL,
    [UpdatedTmstmp]                 DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]                 CHAR (8)       NOT NULL,
    [LastActionCd]                  CHAR (1)       NOT NULL,
    [SourceSystemCd]                CHAR (2)       NOT NULL,
    CONSTRAINT [PK_FarmQuoteUnitEndorsement] PRIMARY KEY CLUSTERED ([UnitNbr] ASC, [UnitTypeCd] ASC, [QuoteNbr] ASC, [EndorsementId] ASC),
    CONSTRAINT [FK_FarmUnitQuoteEndorsement_Endorsements_01] FOREIGN KEY ([EndorsementId]) REFERENCES [dbo].[Endorsements] ([EndorsementId]),
    CONSTRAINT [FK_FarmUnitQuoteEndorsement_FarmUnitQuote_01] FOREIGN KEY ([UnitNbr], [UnitTypeCd], [QuoteNbr]) REFERENCES [dbo].[FarmQuoteUnit] ([UnitNbr], [UnitTypeCd], [QuoteNbr])
);

