CREATE TABLE [dbo].[FarmPolicy] (
    [PolicyId]                               INT            NOT NULL,
    [PolicyNbr]                              VARCHAR (16)   NOT NULL,
    [AdditionalInsuredPersonsCnt]            INT            NULL,
    [AdditionalLivingUnitsNbr]               INT            NULL,
    [AcresCoveredNbr]                        INT            NULL,
    [FarmOwnerPolicyTypeCd]                  CHAR (1)       NULL,
    [HeatByWoodBurningStoveInd]              CHAR (1)       NULL,
    [SpecialRiskCd]                          CHAR (2)       NULL,
    [MainDewellingsNbr]                      INT            NULL,
    [ExtraFarmsInd]                          CHAR (1)       NULL,
    [ExtraAdditionalResidencePremisesInd]    CHAR (1)       NULL,
    [ExtraOutBuildingsInd]                   CHAR (1)       NULL,
    [ExtraMortgageesInd]                     CHAR (1)       NULL,
    [ComputerRatedLevelCd]                   CHAR (1)       NULL,
    [ActiveAutoPolicyDiscountInd]            CHAR (1)       NULL,
    [TotalLiabilityLocationNbr]              INT            NULL,
    [IRPMPct]                                INT            NULL,
    [IRPMPhysicalConditionPct]               DECIMAL (5, 2) NULL,
    [IRPMClaimsPct]                          DECIMAL (5, 2) NULL,
    [AlInsuranceCreditScoreCd]               CHAR (2)       NULL,
    [SpecialDiscountAmt]                     INT            NULL,
    [CategoryCd]                             CHAR (2)       NULL,
    [ExposureCd]                             CHAR (2)       NULL,
    [ClaimScoreCnt]                          INT            NULL,
    [FarmExposureCd]                         CHAR (1)       NULL,
    [ACV80InsuranceInd]                      CHAR (1)       NULL,
    [PhysicalCharDebitNbr]                   INT            NULL,
    [PhysicalCharDesc]                       VARCHAR (255)  NULL,
    [PropertyInsuranceScoreCnt]              INT            NULL,
    [ScheduledEquipmentInd]                  CHAR (1)       NULL,
    [SpecialDiscountPct]                     DECIMAL (5, 2) NULL,
    [SurchargeExemptInd]                     CHAR (1)       NULL,
    [TotalEquipmentPersonalPropertyLimitAmt] DECIMAL (9)    NULL,
    [ReinsuranceCategoryCd]                  CHAR (2)       NULL,
    [CurrentCustomerInd]                     CHAR (1)       NULL,
    [EQAddDt]                                DATE           NULL,
    [EQRemoveDt]                             DATE           NULL,
    [FireProtectionClassCd]                  CHAR (10)      NULL,
    [FireProtectionAreaNm]                   VARCHAR (300)  NULL,
    [MineSubsidenceCoverageCd]               CHAR (1)       NULL,
    [CoverageDeductibleCd]                   CHAR (3)       NULL,
    [CoverageDeductibleAmt]                  DECIMAL (5)    NULL,
    [CoverageDedWindHailAmt]                 DECIMAL (9)    NULL,
    [TotalAIPPremiumAmt]                     DECIMAL (9, 2) NULL,
    [ClaimScoreDt]                           DATE           NULL,
    [RoofFCTRUsedInd]                        CHAR (1)       NULL,
    [UpdatedTmstmp]                          DATETIME2 (7)  NOT NULL,
    [LocationcountyNbr]                      CHAR (3)       NULL,
    [RoofDefaultInd]                         CHAR (1)       NULL,
    [UserUpdatedId]                          CHAR (8)       NOT NULL,
    [LastActionCd]                           CHAR (1)       NOT NULL,
    [SourceSystemCd]                         CHAR (2)       NOT NULL,
    CONSTRAINT [PK_FarmPolicy] PRIMARY KEY CLUSTERED ([PolicyId] ASC) ON [POLICYCD],
    CONSTRAINT [FK_FarmPolicy_Policy_01] FOREIGN KEY ([PolicyId]) REFERENCES [dbo].[Policy] ([PolicyId])
) ON [POLICYCD];

