CREATE TABLE [dbo].[FarmQuote] (
    [QuoteNbr]                               VARCHAR (16)   NOT NULL,
    [AdditionalInsuredPersonsCnt]            INT            NULL,
    [ActiveAutoPolicyDiscountInd]            CHAR (1)       NULL,
    [AlInsuranceCreditScoreCd]               CHAR (2)       NULL,
    [SpecialDiscountAmt]                     INT            NULL,
    [ExposureCd]                             CHAR (2)       NULL,
    [ClaimScoreCnt]                          INT            NULL,
    [FarmExposureCd]                         CHAR (1)       NULL,
    [ACV80InsuranceInd]                      CHAR (1)       NULL,
    [PhysicalCharDebitNbr]                   INT            NULL,
    [PhysicalCharDesc]                       VARCHAR (255)  NULL,
    [PropertyInsuranceScoreCnt]              INT            NULL,
    [ScheduledEquipmentInd]                  CHAR (1)       NULL,
    [SpecialDiscountPct]                     DECIMAL (5, 2) NULL,
    [SurchargeExemptInd]                     CHAR (1)       NULL,
    [TotalEquipmentPersonalPropertyLimitAmt] DECIMAL (9)    NULL,
    [ReinsuranceCategoryCd]                  CHAR (2)       NULL,
    [CurrentCustomerInd]                     CHAR (1)       NULL,
    [EQAddDt]                                DATE           NULL,
    [EQRemoveDt]                             DATE           NULL,
    [ComputerRatedLevelCd]                   CHAR (1)       NULL,
    [CoverageDeductibleCd]                   CHAR (3)       NULL,
    [CoverageDeductibleAmt]                  DECIMAL (5)    NULL,
    [CoverageDedWindHailAmt]                 DECIMAL (9)    NULL,
    [TotalAIPPremiumAmt]                     DECIMAL (9, 2) NULL,
    [ClaimScoreDt]                           DATE           NULL,
    [UpdatedTmstmp]                          DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]                          CHAR (8)       NOT NULL,
    [LastActionCd]                           CHAR (1)       NOT NULL,
    [SourceSystemCd]                         CHAR (2)       NOT NULL,
    CONSTRAINT [PK_FarmQuote] PRIMARY KEY CLUSTERED ([QuoteNbr] ASC) ON [POLICYCD],
    CONSTRAINT [FK_FarmQuote_Quote_01] FOREIGN KEY ([QuoteNbr]) REFERENCES [dbo].[Quote] ([QuoteNbr])
) ON [POLICYCD];

