CREATE TABLE [dbo].[HomePolicy] (
    [PolicyId]                    INT            NOT NULL,
    [PolicyNbr]                   VARCHAR (16)   NOT NULL,
    [CurrentCustomerInd]          CHAR (1)       NULL,
    [ActiveAutoPolicyDiscountInd] CHAR (1)       NULL,
    [SurchargeExemptInd]          CHAR (1)       NULL,
    [ActiveAutoFctr]              DECIMAL (4, 3) NULL,
    [PropertyCreditScoreFctr]     DECIMAL (4, 3) NULL,
    [ReinsuranceCategoryCd]       CHAR (2)       NULL,
    [ComputerRatedLevelCd]        CHAR (1)       NULL,
    [InflationGuardCd]            CHAR (1)       NULL,
    [AlInsuranceCreditScoreCd]    CHAR (2)       NULL,
    [ClaimScoreCnt]               INT            NULL,
    [PicturesSubmittedInd]        CHAR (1)       NULL,
    [LossesSinceLapseCnt]         INT            NULL,
    [AdditionalResidencesCnt]     INT            NULL,
    [ClaimScoreDt]                DATE           NULL,
    [RoofFCTRUUsedInd]            CHAR (1)       NULL,
    [UpdatedTmstmp]               DATETIME2 (7)  NOT NULL,
    [AformNbr]                    CHAR (1)       NULL,
    [RoofDefaultInd]              CHAR (1)       NULL,
    [seasonInd]                   CHAR (1)       NULL,
    [UserUpdatedId]               CHAR (8)       NOT NULL,
    [PremiumGroupNbr]             CHAR (2)       NULL,
    [LastActionCd]                CHAR (1)       NOT NULL,
    [SourceSystemCd]              CHAR (2)       NOT NULL,
    CONSTRAINT [PK_HomePolicy] PRIMARY KEY CLUSTERED ([PolicyId] ASC) ON [POLICYCD],
    CONSTRAINT [FK_HomePolicy_Policy_01] FOREIGN KEY ([PolicyId]) REFERENCES [dbo].[Policy] ([PolicyId])
) ON [POLICYCD];

