CREATE TABLE [dbo].[HomeQuoteUnitEQEndorsementDetail] (
    [QuoteNbr]              VARCHAR (16)   NOT NULL,
    [UnitNbr]               INT            NOT NULL,
    [EndorsementId]         INT            NOT NULL,
    [ItemNbr]               CHAR (3)       NOT NULL,
    [EndorsementNbr]        CHAR (10)      NOT NULL,
    [AddressLine1Desc]      VARCHAR (100)  NULL,
    [AddressLine2Desc]      VARCHAR (100)  NULL,
    [AddressLine3Desc]      VARCHAR (100)  NULL,
    [CityNm]                CHAR (30)      NULL,
    [StateOrProvinceCd]     CHAR (3)       NULL,
    [ZipCd]                 CHAR (9)       NULL,
    [EndorsementLimitCd]    CHAR (3)       NULL,
    [EndorsementLimitAmt]   DECIMAL (9)    NULL,
    [EndorsementPremiumAmt] DECIMAL (9, 2) NULL,
    [ConstructionTypeDesc]  CHAR (50)      NULL,
    [StructureDesc]         VARCHAR (255)  NULL,
    [UpdatedTmstmp]         DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]         CHAR (8)       NOT NULL,
    [LastActionCd]          CHAR (1)       NOT NULL,
    [SourceSystemCd]        CHAR (2)       NOT NULL,
    CONSTRAINT [PK_HomeQuoteUnitEQEndorsementDetail] PRIMARY KEY CLUSTERED ([QuoteNbr] ASC, [UnitNbr] ASC, [EndorsementId] ASC, [ItemNbr] ASC) ON [POLICYCD],
    CONSTRAINT [FK_HomeQuoteUnitEQEndorsementDetail_HomeQuoteUnitEndorsement_01] FOREIGN KEY ([QuoteNbr], [UnitNbr], [EndorsementId]) REFERENCES [dbo].[HomeQuoteUnitEndorsement] ([QuoteNbr], [UnitNbr], [EndorsementId])
) ON [POLICYCD];

