CREATE TABLE [dbo].[HomeUnit] (
    [UnitNbr]                           INT            NOT NULL,
    [PolicyId]                          INT            NOT NULL,
    [PolicyNbr]                         VARCHAR (16)   NOT NULL,
    [PurchaseDt]                        DATE           NULL,
    [UnitAddedDt]                       DATE           NULL,
    [UnitInceptionDt]                   DATE           NULL,
    [EQAddDt]                           DATE           NULL,
    [EQRemoveDt]                        DATE           NULL,
    [ResidenceTypeDesc]                 VARCHAR (50)   NULL,
    [AddressLine1Desc]                  VARCHAR (100)  NULL,
    [AddressLine2Desc]                  VARCHAR (100)  NULL,
    [AddressLine3Desc]                  VARCHAR (100)  NULL,
    [CityNm]                            CHAR (30)      NULL,
    [LocationCountyNbr]                 CHAR (3)       NULL,
    [StateOrProvinceCd]                 CHAR (3)       NULL,
    [ZipCd]                             CHAR (9)       NULL,
    [DwellingStatusDesc]                VARCHAR (50)   NULL,
    [PrincipalResidenceInsuredInd]      CHAR (1)       NULL,
    [PrincipalResidencePolicyNbr]       VARCHAR (16)   NULL,
    [ResidenceEmployeeCnt]              INT            NULL,
    [NumberFamiliesCnt]                 CHAR (3)       NULL,
    [BuildersRiskInd]                   CHAR (1)       NULL,
    [ConstructionYearDt]                CHAR (4)       NULL,
    [ResidenceAgeNbr]                   DECIMAL (5, 2) NULL,
    [PhysicalCharDebitNbr]              INT            NULL,
    [PhysicalCharDesc]                  VARCHAR (255)  NULL,
    [OccupancyTypeCd]                   CHAR (1)       NULL,
    [ProtectionClassCd]                 VARCHAR (2)    NULL,
    [ConstructionTypeCd]                CHAR (2)       NULL,
    [ConstructionTypeDesc]              CHAR (50)      NULL,
    [ZoneCd]                            CHAR (2)       NULL,
    [DistanceFromHydrantCd]             CHAR (2)       NULL,
    [DistanceFromFireStationCd]         CHAR (2)       NULL,
    [RPMConditionCd]                    CHAR (1)       NULL,
    [ExceptionCd]                       CHAR (1)       NULL,
    [RatingTerritoryCd]                 CHAR (2)       NULL,
    [RateClassCd]                       CHAR (1)       NULL,
    [SubRatePlanCd]                     CHAR (1)       NULL,
    [PrimaryHeatingDesc]                VARCHAR (50)   NULL,
    [PrimaryHeatingOtherDesc]           VARCHAR (50)   NULL,
    [SprinklerSystemTypeDesc]           VARCHAR (50)   NULL,
    [HeatingUpgradeYearDt]              CHAR (4)       NULL,
    [PlumbingUpgradeYearDt]             CHAR (4)       NULL,
    [WiriingUpgradeYearDt]              CHAR (4)       NULL,
    [HO256LossSettlementCoInsurancePct] INT            NULL,
    [IRPMPhysicalConditionPct]          DECIMAL (5, 2) NULL,
    [IRPMClaimsPct]                     DECIMAL (5, 2) NULL,
    [AptsInFireWallCnt]                 CHAR (3)       NULL,
    [FireProtectionAreaNm]              VARCHAR (300)  NULL,
    [LegalAddressDesc]                  VARCHAR (300)  NULL,
    [OtherInsuranceInd]                 CHAR (1)       NULL,
    [OtherInsuranceDesc]                VARCHAR (255)  NULL,
    [MultipleStructureInd]              CHAR (1)       NULL,
    [TypeOfStructureDesc]               VARCHAR (255)  NULL,
    [SwimmingPoolInd]                   CHAR (1)       NULL,
    [DivingBoardInd]                    CHAR (1)       NULL,
    [FencedOrGatedInd]                  CHAR (1)       NULL,
    [FireExtinguishersInd]              CHAR (1)       NULL,
    [BurglarAlarmInd]                   CHAR (1)       NULL,
    [BurglurAlarmTypeDesc]              VARCHAR (255)  NULL,
    [FireAlarmInd]                      CHAR (1)       NULL,
    [FireAlarmTypeDesc]                 VARCHAR (255)  NULL,
    [SmokeAlarmInd]                     CHAR (1)       NULL,
    [DeadboltInd]                       CHAR (1)       NULL,
    [ContractorBuiltInd]                CHAR (1)       NULL,
    [PreviouslyInsuredDesc]             VARCHAR (255)  NULL,
    [PremiumGroupCd]                    CHAR (2)       NULL,
    [PreviouslyInsuredInd]              CHAR (1)       NULL,
    [PermanentlyAffixedToRealtyInd]     CHAR (1)       NULL,
    [ExchangedTitleForDeedInd]          CHAR (1)       NULL,
    [RoofRatingFctr]                    DECIMAL (4, 3) NULL,
    [ProtectiveDevicesFctr]             DECIMAL (4, 3) NULL,
    [PropertyPlusFctr]                  DECIMAL (4, 3) NULL,
    [MineSubsidenceCoverageCd]          CHAR (1)       NULL,
    [PhysicalCharacterRatedTotalNbr]    INT            NULL,
    [RoofYearVerifiedInd]               CHAR (1)       NULL,
    [UpdatedTmstmp]                     DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]                     CHAR (8)       NOT NULL,
    [LastActionCd]                      CHAR (1)       NOT NULL,
    [SourceSystemCd]                    CHAR (2)       NOT NULL,
    CONSTRAINT [PK_HomeUnit] PRIMARY KEY CLUSTERED ([PolicyId] ASC, [UnitNbr] ASC) ON [POLICYCD],
    CONSTRAINT [FK_HomeUnit_HomePolicy_01] FOREIGN KEY ([PolicyId]) REFERENCES [dbo].[HomePolicy] ([PolicyId])
) ON [POLICYCD];


GO
CREATE NONCLUSTERED INDEX [IX_HomeUnit_01]
    ON [dbo].[HomeUnit]([PolicyId] ASC)
    ON [POLICYCI];

