CREATE TABLE [dbo].[HomeQuoteUnit] (
    [QuoteNbr]                       VARCHAR (16)   NOT NULL,
    [UnitNbr]                        INT            NOT NULL,
    [PurchaseDt]                     DATE           NULL,
    [ResidenceTypeDesc]              VARCHAR (50)   NULL,
    [AddressLine1Desc]               VARCHAR (100)  NULL,
    [AddressLine2Desc]               VARCHAR (100)  NULL,
    [AddressLine3Desc]               VARCHAR (100)  NULL,
    [CityNm]                         CHAR (30)      NULL,
    [LocationCountyNbr]              CHAR (3)       NULL,
    [StateOrProvinceCd]              CHAR (3)       NULL,
    [ZipCd]                          CHAR (9)       NULL,
    [MineSubsidenceCoverageCd]       CHAR (1)       NULL,
    [PrincipalResidenceInsuredInd]   CHAR (1)       NULL,
    [PrincipalResidencePolicyNbr]    VARCHAR (16)   NULL,
    [DwellingStatusDesc]             VARCHAR (50)   NULL,
    [ResidenceEmployeeCnt]           INT            NULL,
    [NumberFamiliesCnt]              CHAR (3)       NULL,
    [BuildersRiskInd]                CHAR (1)       NULL,
    [ConstructionYearDt]             CHAR (4)       NULL,
    [ResidenceAgeNbr]                DECIMAL (5, 2) NULL,
    [PhysicalCharDebitNbr]           INT            NULL,
    [PhysicalCharDesc]               VARCHAR (255)  NULL,
    [OccupancyTypeCd]                CHAR (1)       NULL,
    [ProtectionClassCd]              VARCHAR (2)    NULL,
    [ConstructionTypeCd]             CHAR (2)       NULL,
    [ConstructionTypeDesc]           CHAR (50)      NULL,
    [ZoneCd]                         CHAR (2)       NULL,
    [DistanceFromHydrantCd]          CHAR (2)       NULL,
    [DistanceFromFireStationCd]      CHAR (2)       NULL,
    [RatingTerritoryCd]              CHAR (2)       NULL,
    [RateClassCd]                    CHAR (1)       NULL,
    [SubRatePlanCd]                  CHAR (1)       NULL,
    [PrimaryHeatingDesc]             VARCHAR (50)   NULL,
    [PrimaryHeatingOtherDesc]        VARCHAR (50)   NULL,
    [SprinklerSystemTypeDesc]        VARCHAR (50)   NULL,
    [HeatingUpgradeYearDt]           CHAR (4)       NULL,
    [PlumbingUpgradeYearDt]          CHAR (4)       NULL,
    [WiriingUpgradeYearDt]           CHAR (4)       NULL,
    [AptsInFireWallCnt]              CHAR (3)       NULL,
    [FireProtectionAreaNm]           VARCHAR (300)  NULL,
    [OtherInsuranceInd]              CHAR (1)       NULL,
    [OtherInsuranceDesc]             VARCHAR (255)  NULL,
    [MultipleStructureInd]           CHAR (1)       NULL,
    [TypeOfStructureDesc]            VARCHAR (255)  NULL,
    [SwimmingPoolInd]                CHAR (1)       NULL,
    [DivingBoardInd]                 CHAR (1)       NULL,
    [FencedOrGatedInd]               CHAR (1)       NULL,
    [FireExtinguishersInd]           CHAR (1)       NULL,
    [BurglarAlarmInd]                CHAR (1)       NULL,
    [BurglurAlarmTypeDesc]           VARCHAR (255)  NULL,
    [FireAlarmInd]                   CHAR (1)       NULL,
    [FireAlarmTypeDesc]              VARCHAR (255)  NULL,
    [SmokeAlarmInd]                  CHAR (1)       NULL,
    [DeadboltInd]                    CHAR (1)       NULL,
    [ContractorBuiltInd]             CHAR (1)       NULL,
    [PermanentlyAffixedToRealtyInd]  CHAR (1)       NULL,
    [ExchangedTitleForDeedInd]       CHAR (1)       NULL,
    [PreviouslyInsuredDesc]          VARCHAR (255)  NULL,
    [PremiumGroupCd]                 CHAR (2)       NULL,
    [PreviouslyInsuredInd]           CHAR (1)       NULL,
    [RoofRatingFctr]                 DECIMAL (4, 3) NULL,
    [ProtectiveDevicesFctr]          DECIMAL (4, 3) NULL,
    [PropertyPlusFctr]               DECIMAL (4, 3) NULL,
    [PhysicalCharacterRatedTotalNbr] INT            NULL,
    [UpdatedTmstmp]                  DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]                  CHAR (8)       NOT NULL,
    [LastActionCd]                   CHAR (1)       NOT NULL,
    [SourceSystemCd]                 CHAR (2)       NOT NULL,
    CONSTRAINT [PK_HomeQuoteUnit] PRIMARY KEY CLUSTERED ([QuoteNbr] ASC, [UnitNbr] ASC) ON [POLICYCD],
    CONSTRAINT [FK_HomeQuoteUnit_HomeQuote_01] FOREIGN KEY ([QuoteNbr]) REFERENCES [dbo].[HomeQuote] ([QuoteNbr])
) ON [POLICYCD];

