CREATE TABLE [dbo].[Litigation] (
    [LitigationId]              INT             NOT NULL,
    [ResolutionTypeId]          INT             NULL,
    [ReopenedReasonId]          INT             NULL,
    [AssignmentStatusId]        INT             NULL,
    [CasePrimaryCauseId]        INT             NULL,
    [LawSuitTypeId]             INT             NULL,
    [MethodServedId]            INT             NULL,
    [CourtDistrictId]           INT             NULL,
    [CourtTypeId]               INT             NULL,
    [LegalSpecialtyId]          INT             NULL,
    [MatterStateId]             INT             NULL,
    [PlaintiffAttorneyId]       INT             NULL,
    [DefendantId]               INT             NULL,
    [LitigationDesc]            VARCHAR (2000)  NULL,
    [DeclaratoryJudgementInd]   CHAR (1)        NULL,
    [FinalSettlementAmt]        DECIMAL (18, 2) NULL,
    [AssignmentDt]              DATE            NULL,
    [StructuredSettlementInd]   CHAR (1)        NULL,
    [MediationDt]               DATE            NULL,
    [ArbitrationInd]            CHAR (1)        NULL,
    [TrialDt]                   DATE            NULL,
    [ExtensionDt]               DATE            NULL,
    [FileDt]                    DATE            NULL,
    [DefenseAppointmentDt]      DATE            NULL,
    [CaseNm]                    VARCHAR (128)   NULL,
    [CaseNbr]                   VARCHAR (100)   NULL,
    [DepositionRequiredInd]     CHAR (1)        NULL,
    [MotionSummaryJudgementInd] CHAR (1)        NULL,
    [CaseCloseDt]               DATE            NULL,
    [FinalSettlementDt]         DATE            NULL,
    [ResponseFiledDt]           DATE            NULL,
    [SubroRelatedInd]           CHAR (1)        NULL,
    [DocketNbr]                 VARCHAR (20)    NULL,
    [ArbitrationDt]             DATE            NULL,
    [PunitiveDamagesInd]        CHAR (1)        NULL,
    [FinalLegalAmt]             DECIMAL (18, 2) NULL,
    [LitigationServiceDt]       DATE            NULL,
    [UpdatedTmstmp]             DATETIME2 (7)   NOT NULL,
    [UserUpdatedId]             CHAR (8)        NOT NULL,
    [LastActionCd]              CHAR (1)        NOT NULL,
    [SourceSystemCd]            CHAR (2)        NOT NULL,
    [SourceSystemId]            INT             NOT NULL,
    [ClaimUserCreateTime]       DATETIME2 (7)   NOT NULL,
    [ClaimUserCreatedId]        CHAR (8)        NOT NULL,
    [ClaimUserUpdatedId]        CHAR (8)        NOT NULL,
    [ClaimUpdatedTmstmp]        DATETIME2 (7)   NOT NULL,
    [CurrentRecordInd]          BIT             NOT NULL,
    [RetiredInd]                CHAR (1)        NOT NULL,
    [PlaintiffFirmId]           INT             NULL,
    [DefenseAttorneyId]         INT             NULL,
    [PlaintiffId]               INT             NULL,
    [DefenseFirmId]             INT             NULL,
    [JudgeId]                   INT             NULL,
    [RiskTypeId]                INT             NULL,
    [MatterTypeId]              INT             NULL,
    [LitigationCountyId]        INT             NULL,
    CONSTRAINT [PK_Litigation] PRIMARY KEY CLUSTERED ([LitigationId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_Litigation_ClaimCodeLookup_01] FOREIGN KEY ([MatterStateId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Litigation_ClaimCodeLookup_02] FOREIGN KEY ([ResolutionTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Litigation_ClaimCodeLookup_03] FOREIGN KEY ([ReopenedReasonId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Litigation_ClaimCodeLookup_04] FOREIGN KEY ([AssignmentStatusId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Litigation_ClaimCodeLookup_05] FOREIGN KEY ([CasePrimaryCauseId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Litigation_ClaimCodeLookup_06] FOREIGN KEY ([LawSuitTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Litigation_ClaimCodeLookup_07] FOREIGN KEY ([MethodServedId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Litigation_ClaimCodeLookup_09] FOREIGN KEY ([CourtDistrictId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Litigation_ClaimCodeLookup_10] FOREIGN KEY ([CourtTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Litigation_ClaimCodeLookup_11] FOREIGN KEY ([LegalSpecialtyId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Litigation_ClaimCodeLookup_12] FOREIGN KEY ([MatterTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Litigation_ClaimCodeLookup_14] FOREIGN KEY ([LitigationCountyId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Litigation_Party_01] FOREIGN KEY ([DefenseFirmId]) REFERENCES [dbo].[Party] ([PartyId]),
    CONSTRAINT [FK_Litigation_Party_02] FOREIGN KEY ([PlaintiffFirmId]) REFERENCES [dbo].[Party] ([PartyId]),
    CONSTRAINT [FK_Litigation_Party_03] FOREIGN KEY ([JudgeId]) REFERENCES [dbo].[Party] ([PartyId]),
    CONSTRAINT [FK_Litigation_Party_04] FOREIGN KEY ([DefenseAttorneyId]) REFERENCES [dbo].[Party] ([PartyId]),
    CONSTRAINT [FK_Litigation_Party_05] FOREIGN KEY ([PlaintiffAttorneyId]) REFERENCES [dbo].[Party] ([PartyId]),
    CONSTRAINT [FK_Litigation_Party_06] FOREIGN KEY ([PlaintiffId]) REFERENCES [dbo].[Party] ([PartyId]),
    CONSTRAINT [FK_Litigation_Party_07] FOREIGN KEY ([DefendantId]) REFERENCES [dbo].[Party] ([PartyId]),
    CONSTRAINT [FK_Litigaton_ClaimCodeLookup_13] FOREIGN KEY ([RiskTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId])
) ON [CLAIMSCD];

