CREATE TABLE [dbo].[LossEvent] (
    [LossEventId]                INT             NOT NULL,
    [LossEventSubTypeId]         INT             NOT NULL,
    [LossEventDesc]              VARCHAR (250)   NULL,
    [LossEstimatedAmt]           DECIMAL (11, 2) NULL,
    [UpdatedTmstmp]              DATETIME2 (7)   NOT NULL,
    [UserUpdatedId]              CHAR (8)        NOT NULL,
    [LastActionCd]               CHAR (1)        NOT NULL,
    [SourceSystemCd]             CHAR (2)        NOT NULL,
    [SourceSystemId]             INT             NOT NULL,
    [ClaimUserCreateTime]        DATETIME2 (7)   NOT NULL,
    [ClaimUserCreatedId]         CHAR (8)        NOT NULL,
    [ClaimUpdatedTmstmp]         DATETIME2 (7)   NOT NULL,
    [ClaimUserUpdatedId]         CHAR (8)        NOT NULL,
    [CurrentRecordInd]           BIT             NOT NULL,
    [RetiredInd]                 CHAR (1)        NOT NULL,
    [LodgingStartDt]             DATE            NULL,
    [AssessmentCloseDt]          DATE            NULL,
    [AssessmentComment]          VARCHAR (255)   NULL,
    [AssessmentNm]               VARCHAR (128)   NULL,
    [AssessmentStatusId]         INT             NULL,
    [AssessmentTargetCloseDt]    DATE            NULL,
    [AssessmentTypeId]           INT             NULL,
    [IncludeContentLineItemsInd] CHAR (1)        NULL,
    [IncdAssignmentSentInd]      CHAR (1)        NULL,
    [InspectionComment]          VARCHAR (255)   NULL,
    [InspectionLocationNm]       VARCHAR (80)    NULL,
    [InspectionTypeId]           INT             NULL,
    [InspectionLocationPhone]    VARCHAR (16)    NULL,
    [SeverityTypeId]             INT             NULL,
    [LodgingProviderId]          INT             NULL,
    [ClaimCodeLookupId]          INT             NULL,
    CONSTRAINT [PK_LossEvent] PRIMARY KEY CLUSTERED ([LossEventId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_LossEvent_ClaimCodeLookup_01] FOREIGN KEY ([LossEventSubTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_LossEvent_ClaimCodeLookup_02] FOREIGN KEY ([ClaimCodeLookupId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_LossEvent_ClaimCodeLookup_03] FOREIGN KEY ([AssessmentStatusId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_LossEvent_ClaimCodeLookup_04] FOREIGN KEY ([AssessmentTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_LossEvent_ClaimCodeLookup_05] FOREIGN KEY ([InspectionTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_LossEvent_ClaimCodeLookup_06] FOREIGN KEY ([SeverityTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_LossEvent_Party_01] FOREIGN KEY ([LodgingProviderId]) REFERENCES [dbo].[Party] ([PartyId])
) ON [CLAIMSCD];

