CREATE TABLE [dbo].[MedicareIncident] (
    [MedicareIncidentId]        INT            NOT NULL,
    [MassTortLocationCountryCd] CHAR (2)       NULL,
    [StateOfVenueCd]            CHAR (3)       NULL,
    [SelfInsuredTypeId]         INT            NULL,
    [CMSProductLiabilityId]     INT            NULL,
    [CMSProductAllegedHarmDesc] VARCHAR (2000) NULL,
    [CMSProductBrandNm]         VARCHAR (40)   NULL,
    [CMSProductGenericNm]       VARCHAR (40)   NULL,
    [CMSProductMFGDes]          VARCHAR (40)   NULL,
    [SelfInsuredInd]            CHAR (1)       NULL,
    [IncidentDesc]              VARCHAR (200)  NULL,
    [InjuryClaimantNm]          VARCHAR (75)   NULL,
    [UpdatedTmstmp]             DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]             CHAR (8)       NOT NULL,
    [LastActionCd]              CHAR (1)       NOT NULL,
    [SourceSystemCd]            CHAR (2)       NOT NULL,
    [SourceSystemId]            INT            NOT NULL,
    [ClaimUserCreateTime]       DATETIME2 (7)  NOT NULL,
    [ClaimUserCreatedId]        CHAR (8)       NOT NULL,
    [ClaimUserUpdatedId]        CHAR (8)       NOT NULL,
    [ClaimUpdatedTmstmp]        DATETIME2 (7)  NOT NULL,
    [RetiredInd]                CHAR (1)       NOT NULL,
    [CurrentRecordInd]          BIT            NOT NULL,
    CONSTRAINT [PK_MedicareIncident] PRIMARY KEY CLUSTERED ([MedicareIncidentId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_MedicareIncident_ClaimCodeLookup_02] FOREIGN KEY ([SelfInsuredTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_MedicareIncident_ClaimCodeLookup_03] FOREIGN KEY ([CMSProductLiabilityId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId])
) ON [CLAIMSCD];

