CREATE TABLE [dbo].[PartyLongNameAddress] (
    [PartyLongNameAddressId]      INT           NOT NULL,
    [ClientReferenceNbr]          CHAR (10)     NOT NULL,
    [SequenceNbr]                 CHAR (3)      NULL,
    [NameAddressNbr]              CHAR (3)      NULL,
    [EffectiveDt]                 DATE          NULL,
    [NameOrAddressInd]            CHAR (2)      NULL,
    [LongNameOrLongAddress1Txt]   VARCHAR (60)  NULL,
    [LongNameOrLongAddress2Txt]   VARCHAR (60)  NULL,
    [LongNameOrLongAddress3Txt]   VARCHAR (60)  NULL,
    [LongNameOrLongAddress4Txt]   VARCHAR (60)  NULL,
    [LongNameOrLongAddress5Txt]   VARCHAR (60)  NULL,
    [LongNameOrLongAddress6Txt]   VARCHAR (60)  NULL,
    [LongNameOrLongAddress7Txt]   VARCHAR (60)  NULL,
    [LongNameOrLongAddress8Txt]   VARCHAR (60)  NULL,
    [LongNameOrLongAddress9Txt]   VARCHAR (60)  NULL,
    [LongNameOrLongAddress10Txt]  VARCHAR (60)  NULL,
    [LongNameOrLongAddress11Txt]  VARCHAR (60)  NULL,
    [LongNameOrLongAddress12Text] VARCHAR (60)  NULL,
    [SourceSystemUpdatedTmstmp]   DATETIME2 (7) NULL,
    [SourceSystemUserUpdatedId]   CHAR (10)     NULL,
    [SourceSystemCd]              CHAR (2)      NOT NULL,
    [UpdatedTmstmp]               DATETIME2 (7) NOT NULL,
    [UserUpdatedId]               CHAR (8)      NOT NULL,
    [LastActionCd]                CHAR (1)      NOT NULL,
    CONSTRAINT [PK_PartyLongNameAddress] PRIMARY KEY CLUSTERED ([PartyLongNameAddressId] ASC) ON [CLIENTCD],
    CONSTRAINT [FK_PartyLongNameAddress_PartyMaster_01] FOREIGN KEY ([ClientReferenceNbr]) REFERENCES [dbo].[PartyMaster] ([ClientReferenceNbr])
) ON [CLIENTCD];

