CREATE TABLE [dbo].[PartyAddress] (
    [PartyAddressId]            INT           NOT NULL,
    [ClientReferenceNbr]        CHAR (10)     NOT NULL,
    [EffectiveDt]               DATE          NULL,
    [ExpirationDt]              DATE          NULL,
    [SequenceNbr]               CHAR (3)      NULL,
    [LocationReferenceNbr]      CHAR (3)      NULL,
    [AddressNbr]                CHAR (3)      NULL,
    [AddressCategoryCd]         CHAR (1)      NULL,
    [ISOCountryCd]              CHAR (2)      NULL,
    [StateOrProvinceCd]         CHAR (3)      NULL,
    [CountyNm]                  CHAR (19)     NULL,
    [AddresseeNm]               CHAR (40)     NULL,
    [ExtraAddressInfoTxt]       CHAR (30)     NULL,
    [StreetAddressTxt]          CHAR (35)     NULL,
    [CityNm]                    CHAR (30)     NULL,
    [ZipCd]                     CHAR (10)     NULL,
    [SourceSystemUpdatedTmstmp] DATETIME2 (7) NULL,
    [SourceSystemUserUpdatedId] CHAR (10)     NULL,
    [UpdatedTmstmp]             DATETIME2 (7) NOT NULL,
    [UserUpdatedId]             CHAR (8)      NOT NULL,
    [LastActionCd]              CHAR (1)      NOT NULL,
    [SourceSystemCd]            CHAR (2)      NOT NULL,
    CONSTRAINT [PK_PartyAddress] PRIMARY KEY CLUSTERED ([PartyAddressId] ASC) ON [CLIENTCD],
    CONSTRAINT [FK_PartyAddress_PartyMaster_01] FOREIGN KEY ([ClientReferenceNbr]) REFERENCES [dbo].[PartyMaster] ([ClientReferenceNbr])
) ON [CLIENTCD];

