CREATE TABLE [dbo].[PartyAdditionalDetails] (
    [PartyAdditionalDetailsId]               CHAR (18)     NOT NULL,
    [ClientReferenceNbr]                     CHAR (10)     NOT NULL,
    [SequenceNbr]                            CHAR (3)      NULL,
    [EffectiveDt]                            DATE          NULL,
    [ExpirationDt]                           DATE          NULL,
    [CellPhoneNbr]                           CHAR (16)     NULL,
    [PagerNbr]                               CHAR (16)     NULL,
    [PreferredMethodofContactCd]             CHAR (2)      NULL,
    [EmailAddress1Cd]                        CHAR (2)      NULL,
    [EmailAddress1Desc]                      CHAR (40)     NULL,
    [EmailAddress2Cd]                        CHAR (2)      NULL,
    [EmailAddress2Desc]                      CHAR (40)     NULL,
    [MembershipCardCd]                       CHAR (2)      NULL,
    [ExemptEmployeeInd]                      CHAR (2)      NULL,
    [LicenseNbr]                             VARCHAR (25)  NULL,
    [LicenseStateCd]                         CHAR (2)      NULL,
    [MVRReceivedDt]                          DATE          NULL,
    [BoatSafetyCourseInd]                    CHAR (1)      NULL,
    [SurchargeExemptInd]                     CHAR (1)      NULL,
    [AutoInsuranceScoreNbr]                  INT           NULL,
    [AutoInsuranceScoreReceiptDt]            DATE          NULL,
    [AutoCLUEReportReceivedDt]               DATE          NULL,
    [AllinesPropertyInsuranceScoreNbr]       INT           NULL,
    [AllinesPropertyInsuranceScoreReceiptDt] DATE          NULL,
    [AllinesPropertyCLUEReportReceiptDt]     DATE          NULL,
    [SourceSystemUpdatedTmstmp]              DATETIME2 (7) NULL,
    [SourceSystemUserUpdatedId]              CHAR (10)     NULL,
    [UpdatedTmstmp]                          DATETIME2 (7) NOT NULL,
    [UserUpdatedId]                          CHAR (8)      NOT NULL,
    [LastActionCd]                           CHAR (1)      NOT NULL,
    [SourceSystemCd]                         CHAR (2)      NOT NULL,
    CONSTRAINT [PK_PartyAdditionalDetails] PRIMARY KEY CLUSTERED ([PartyAdditionalDetailsId] ASC) ON [CLIENTCD],
    CONSTRAINT [FK_PartyAdditionalDetails_PartyMaster_01] FOREIGN KEY ([ClientReferenceNbr]) REFERENCES [dbo].[PartyMaster] ([ClientReferenceNbr])
) ON [CLIENTCD];

