CREATE TABLE [dbo].[PartySupplementalDetails] (
    [PartySupplementalDetailsId] INT           NOT NULL,
    [ClientReferenceNbr]         CHAR (10)     NOT NULL,
    [SequenceNbr]                CHAR (3)      NULL,
    [EffectiveDt]                DATE          NULL,
    [ExpirationDt]               DATE          NULL,
    [ClientRegistrationDt]       DATE          NULL,
    [Phone1Nbr]                  CHAR (16)     NULL,
    [Phone2Nbr]                  CHAR (16)     NULL,
    [Fax1Nbr]                    CHAR (20)     NULL,
    [Fax2Nbr]                    CHAR (20)     NULL,
    [EmployerNm]                 VARCHAR (30)  NULL,
    [OccupationCd]               CHAR (5)      NULL,
    [BusinessCd]                 CHAR (4)      NULL,
    [BankBSBNbr]                 CHAR (8)      NULL,
    [BankNm]                     VARCHAR (30)  NULL,
    [BankAccountNbr]             CHAR (14)     NULL,
    [Contact1Txt]                VARCHAR (40)  NULL,
    [ContactPhone1Nbr]           CHAR (16)     NULL,
    [ContactFax1Nbr]             CHAR (20)     NULL,
    [Contact2Txt]                VARCHAR (40)  NULL,
    [ContactPhone2Nbr]           CHAR (16)     NULL,
    [ContactFax2Nbr]             CHAR (20)     NULL,
    [IdentificationNbr]          VARCHAR (13)  NULL,
    [ReinsuranceCd]              VARCHAR (10)  NULL,
    [InsuranceNbr]               CHAR (15)     NULL,
    [IncomeTurnoverNbr]          VARCHAR (13)  NULL,
    [PayrollInd]                 CHAR (1)      NULL,
    [ChildrenNbr]                INT           NULL,
    [MaritalStatusCd]            CHAR (1)      NULL,
    [SpouseNm]                   VARCHAR (30)  NULL,
    [StatsCd]                    CHAR (2)      NULL,
    [Stats2Cd]                   CHAR (2)      NULL,
    [Stats3Cd]                   CHAR (2)      NULL,
    [Stats4Cd]                   CHAR (2)      NULL,
    [ClientStatusCd]             CHAR (1)      NULL,
    [ClientClassCd]              CHAR (2)      NULL,
    [PreferredLanguageInd]       CHAR (1)      NULL,
    [AgeAdmittedInd]             CHAR (1)      NULL,
    [SexCd]                      CHAR (1)      NULL,
    [DeathDt]                    DATE          NULL,
    [BirthDt]                    DATE          NULL,
    [ResidenceStateCd]           CHAR (2)      NULL,
    [ResidenceMunicipalityCd]    CHAR (3)      NULL,
    [NationalityCd]              VARCHAR (10)  NULL,
    [SourceSystemUpdatedTmstmp]  DATETIME2 (7) NULL,
    [SourceSystemUserUpdatedId]  CHAR (10)     NULL,
    [UpdatedTmstmp]              DATETIME2 (7) NOT NULL,
    [UserUpdatedId]              CHAR (8)      NOT NULL,
    [LastActionCd]               CHAR (1)      NOT NULL,
    [SourceSystemCd]             CHAR (2)      NOT NULL,
    CONSTRAINT [PK_PartySupplementalDetails] PRIMARY KEY CLUSTERED ([PartySupplementalDetailsId] ASC) ON [CLIENTCD],
    CONSTRAINT [FK_PartySupplementalDetails_PartyMaster_01] FOREIGN KEY ([ClientReferenceNbr]) REFERENCES [dbo].[PartyMaster] ([ClientReferenceNbr])
) ON [CLIENTCD];

