CREATE TABLE [dbo].[Payment] (
    [ClaimFinancialTransactionId] INT             NOT NULL,
    [ClaimPaymentId]              INT             NOT NULL,
    [PaymentTypeId]               INT             NULL,
    [FinalReplacementCostPayID]   INT             NULL,
    [SalvageExpenseAmt]           DECIMAL (18, 2) NOT NULL,
    [SubrogationExpenseAmt]       DECIMAL (18, 2) NOT NULL,
    [LossAdjustmentExpenseAmt]    DECIMAL (18, 2) NOT NULL,
    [TotalClaimPayoutAmt]         DECIMAL (11, 2) NOT NULL,
    [DoesNotAffectReservesInd]    CHAR (1)        NULL,
    [UpdatedTmstmp]               DATETIME2 (7)   NOT NULL,
    [ClaimUserCreateTime]         DATETIME2 (7)   NOT NULL,
    [ClaimUserCreatedId]          CHAR (8)        NOT NULL,
    [ClaimUpdatedTmstmp]          DATETIME2 (7)   NOT NULL,
    [ClaimUserUpdatedId]          CHAR (8)        NOT NULL,
    [RetiredInd]                  CHAR (1)        NOT NULL,
    [EQPaymentInd]                CHAR (1)        NULL,
    [SourceSystemId]              INT             NOT NULL,
    [UserUpdatedId]               CHAR (8)        NOT NULL,
    [LastActionCd]                CHAR (1)        NOT NULL,
    [SourceSystemCd]              CHAR (2)        NOT NULL,
    CONSTRAINT [PK_Payment] PRIMARY KEY CLUSTERED ([ClaimFinancialTransactionId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_Payment_ClaimCodeLookup_01] FOREIGN KEY ([ClaimPaymentId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Payment_ClaimCodeLookup_02] FOREIGN KEY ([PaymentTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Payment_ClaimCodeLookup_03] FOREIGN KEY ([FinalReplacementCostPayID]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Payment_ClaimFinancialTransaction_01] FOREIGN KEY ([ClaimFinancialTransactionId]) REFERENCES [dbo].[ClaimFinancialTransaction] ([ClaimFinancialTransactionId])
) ON [CLAIMSCD];

