CREATE TABLE [dbo].[PolicyPremium] (
    [PolicyId]                        INT            NOT NULL,
    [PolicyNbr]                       VARCHAR (16)   NOT NULL,
    [LineofBusinessCd]                CHAR (2)       NOT NULL,
    [SublineBusinessTypeCd]           CHAR (1)       NOT NULL,
    [BasicPolicyPremiumAmt]           DECIMAL (9, 2) NULL,
    [BasicPolicyGrossPremiumAmt]      DECIMAL (9, 2) NULL,
    [AdditionalPremiumAmt]            DECIMAL (9, 2) NULL,
    [EndorsementPolicyPremiumAmt]     DECIMAL (9, 2) NULL,
    [TotalPremiumAmt]                 DECIMAL (9, 2) NULL,
    [TotalTaxAmt]                     DECIMAL (9, 2) NULL,
    [TotalDiscountAmt]                DECIMAL (9, 2) NULL,
    [EQTotalPremiumAmt]               DECIMAL (9, 2) NULL,
    [EQTotalTaxAmt]                   DECIMAL (9, 2) NULL,
    [EQTotalProratedPremiumAmt]       DECIMAL (9, 2) NULL,
    [EQTotalProratedTaxAmt]           DECIMAL (9, 2) NULL,
    [EQEndorsementPremiumAmt]         DECIMAL (9, 2) NULL,
    [EQEndorsementProratedPremiumAmt] DECIMAL (9, 2) NULL,
    [IMLinePremiumAmt]                DECIMAL (9, 2) NULL,
    [UpdatedTmstmp]                   DATETIME2 (7)  NOT NULL,
    [GLLinePremiumAmt]                DECIMAL (9, 2) NULL,
    [UserUpdatedId]                   CHAR (8)       NOT NULL,
    [CPLinePremiumAmount]             DECIMAL (9, 2) NULL,
    [LastActionCd]                    CHAR (1)       NOT NULL,
    [SourceSystemCd]                  CHAR (2)       NOT NULL,
    [SurchargeTaxAmt]                 DECIMAL (9, 2) NULL,
    CONSTRAINT [PK_PolicyPremium] PRIMARY KEY CLUSTERED ([PolicyId] ASC) ON [POLICYCD],
    CONSTRAINT [FK_PolicyPremium_Policy_01] FOREIGN KEY ([PolicyId]) REFERENCES [dbo].[Policy] ([PolicyId])
) ON [POLICYCD];

