CREATE TABLE [dbo].[PolicyLocationDetail] (
    [PolicyId]             INT           NOT NULL,
    [LocationID]           BIGINT        NOT NULL,
    [PolicyNbr]            VARCHAR (16)  NOT NULL,
    [CountyNbr]            CHAR (3)      NOT NULL,
    [TaxCd]                CHAR (4)      NOT NULL,
    [LocationTypeCd]       VARCHAR (50)  NOT NULL,
    [LocationNameDesc]     VARCHAR (255) NULL,
    [LocationDesc]         VARCHAR (255) NULL,
    [TaxJurisdictionNm]    CHAR (40)     NULL,
    [TerritoryCd]          CHAR (3)      NULL,
    [PrimaryLocationInd]   CHAR (1)      NULL,
    [CreatedTmstmp]        DATETIME      NOT NULL,
    [PrimaryLocationIMInd] CHAR (1)      NULL,
    [UserCreatedId]        CHAR (8)      NOT NULL,
    [UpdatedTmstmp]        DATETIME2 (7) NOT NULL,
    [UserUpdatedId]        CHAR (8)      NOT NULL,
    [LastActionCd]         CHAR (1)      NOT NULL,
    [SourceSystemCd]       CHAR (2)      NOT NULL,
    [LocationSequenceNbr]  INT           NULL,
    CONSTRAINT [PK_PolicyLocationDetail] PRIMARY KEY CLUSTERED ([PolicyId] ASC, [LocationID] ASC) ON [POLICYCD],
    CONSTRAINT [FK_PolicyLocationDetail_Location_01] FOREIGN KEY ([LocationID]) REFERENCES [dbo].[Location] ([LocationID]),
    CONSTRAINT [FK_PolicyLocationDetail_Policy_01] FOREIGN KEY ([PolicyId]) REFERENCES [dbo].[Policy] ([PolicyId])
) ON [POLICYCD];

