CREATE TABLE [dbo].[PolicyNotes] (
    [NotesId]                   INT           NOT NULL,
    [PolicyNbr]                 VARCHAR (16)  NOT NULL,
    [LineofBusinessCd]          CHAR (2)      NOT NULL,
    [SublineBusinessTypeCd]     CHAR (1)      NOT NULL,
    [JobTypeDesc]               VARCHAR (255) NULL,
    [AuthoringDt]               DATETIME2 (7) NULL,
    [AuthorNm]                  VARCHAR (255) NULL,
    [TopicDesc]                 VARCHAR (255) NULL,
    [SeverityDesc]              VARCHAR (255) NULL,
    [SubjectDesc]               VARCHAR (255) NULL,
    [ConfidentialInd]           CHAR (1)      NULL,
    [RelatedToDesc]             VARCHAR (255) NULL,
    [NotesTxt]                  TEXT          NULL,
    [SourceSystemPolicyId]      INT           NOT NULL,
    [SourceSystemUserCreatedId] CHAR (10)     NOT NULL,
    [SourceSystemUpdatedTmstmp] DATETIME2 (7) NOT NULL,
    [SourceSystemCreatedTmstmp] DATETIME2 (7) NOT NULL,
    [SourceSystemUserUpdatedId] CHAR (10)     NOT NULL,
    [SourceSystemId]            INT           NOT NULL,
    [CreatedTmstmp]             DATETIME      NOT NULL,
    [UserCreatedId]             CHAR (8)      NOT NULL,
    [UpdatedTmstmp]             DATETIME2 (7) NOT NULL,
    [UserUpdatedId]             CHAR (8)      NOT NULL,
    [LastActionCd]              CHAR (1)      NOT NULL,
    [SourceSystemCd]            CHAR (2)      NOT NULL,
    CONSTRAINT [PK_PolicyPendingActivity_1] PRIMARY KEY CLUSTERED ([NotesId] ASC)
);

