CREATE TABLE [dbo].[PolicyActivitiy] (
    [ActivityId]            INT           IDENTITY (1, 1) NOT NULL,
    [PolicyNbr]             VARCHAR (16)  NOT NULL,
    [LineofBusinessCd]      CHAR (2)      NOT NULL,
    [SublineCd]             CHAR (1)      NOT NULL,
    [ClassCd]               CHAR (5)      NOT NULL,
    [ApprovalIssueDesc]     VARCHAR (255) NULL,
    [ApprovalRationaleDesc] VARCHAR (255) NULL,
    [ApprovedInd]           CHAR (1)      NOT NULL,
    [AssignedByUserID]      CHAR (8)      NOT NULL,
    [AssignedGroupNm]       VARCHAR (100) NULL,
    [AssignedUserID]        CHAR (8)      NOT NULL,
    [AssignedDt]            DATE          NOT NULL,
    [StatusCd]              CHAR (2)      NOT NULL,
    [CloseDt]               DATE          NULL,
    [CloseUserID]           CHAR (8)      NULL,
    [ActivityDesc]          VARCHAR (750) NULL,
    [EscalatedInd]          CHAR (1)      NULL,
    [EscalationDt]          DATE          NULL,
    [BranchNbr]             CHAR (3)      NOT NULL,
    [CountyNbr]             CHAR (3)      NOT NULL,
    [AgencyNbr]             CHAR (3)      NOT NULL,
    [CreatedTmstmp]         DATETIME      NOT NULL,
    [UserCreatedId]         CHAR (8)      NOT NULL,
    [UpdatedTmstmp]         DATETIME2 (7) NOT NULL,
    [UserUpdatedId]         CHAR (8)      NOT NULL,
    [LastActionCd]          CHAR (1)      NOT NULL,
    [SourceSystemCd]        CHAR (2)      NOT NULL,
    CONSTRAINT [PK_PolicyActivitiy] PRIMARY KEY CLUSTERED ([ActivityId] ASC, [PolicyNbr] ASC) ON [POLICYCD]
) ON [POLICYCD];

