CREATE TABLE [dbo].[PropertyLossEvent] (
    [LossEventId]                INT           NOT NULL,
    [PropertyClassTypeId]        INT           NULL,
    [ExternalWallMaterialId]     INT           NULL,
    [LossAreaId]                 INT           NULL,
    [RoofMaterialId]             INT           NULL,
    [SprinklerTypeId]            INT           NULL,
    [InspectionRequiredInd]      CHAR (1)      NULL,
    [PropertyDesc]               VARCHAR (255) NULL,
    [HazardInvolvedInd]          CHAR (1)      NULL,
    [VacantInd]                  CHAR (1)      NULL,
    [UpdatedTmstmp]              DATETIME2 (7) NOT NULL,
    [ClaimUserCreateTime]        DATETIME2 (7) NOT NULL,
    [ClaimUserCreatedId]         CHAR (8)      NOT NULL,
    [ClaimUpdatedTmstmp]         DATETIME2 (7) NOT NULL,
    [ClaimUserUpdatedId]         CHAR (8)      NOT NULL,
    [RetiredInd]                 CHAR (1)      NOT NULL,
    [SourceSystemId]             INT           NOT NULL,
    [UserUpdatedId]              CHAR (8)      NOT NULL,
    [LastActionCd]               CHAR (1)      NOT NULL,
    [SourceSystemCd]             CHAR (2)      NOT NULL,
    [FencesDamagedInd]           CHAR (1)      NULL,
    [DamagedAreaSize]            INT           NULL,
    [DebrisRemovalCoID]          INT           NULL,
    [DebrisRemovalInd]           CHAR (1)      NULL,
    [NumOfRoomsDamaged]          INT           NULL,
    [RoomTypeId]                 INT           NULL,
    [EMSInd]                     CHAR (1)      NULL,
    [FireProtectionAvailableInd] CHAR (1)      NULL,
    [MaterialsDamaged]           VARCHAR (255) NULL,
    [NumOfPeopleOnPolicy]        INT           NULL,
    [PropertySize]               INT           NULL,
    [YearBuilt]                  DATE          NULL,
    [YearsInHome]                INT           NULL,
    [EMSCoId]                    INT           NULL,
    [RoofTypeOtherDesc]          VARCHAR (100) NULL,
    [RoofReplacedYearDt]         CHAR (4)      NULL,
    [RoofTypeId]                 INT           NULL,
    [RoofPitchId]                INT           NULL,
    [RoofShapeId]                INT           NULL,
    [RoofInspectedId]            INT           NULL,
    [RoofFullReplacedId]         INT           NULL,
    CONSTRAINT [PK_PropertyLossEvent] PRIMARY KEY CLUSTERED ([LossEventId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_FixedPropertyLossEvent_ClaimCodeLookUp_01] FOREIGN KEY ([PropertyClassTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_FixedPropertyLossEvent_ClaimCodeLookUp_02] FOREIGN KEY ([ExternalWallMaterialId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_FixedPropertyLossEvent_ClaimCodeLookUp_03] FOREIGN KEY ([LossAreaId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_FixedPropertyLossEvent_ClaimCodeLookUp_04] FOREIGN KEY ([RoofMaterialId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_FixedPropertyLossEvent_ClaimCodeLookUp_05] FOREIGN KEY ([SprinklerTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_FixedPropertyLossEvent_ClaimCodeLookup_07] FOREIGN KEY ([RoomTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_PropertyLossEvent_ClaimCodeLookup_08] FOREIGN KEY ([RoofTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_PropertyLossEvent_ClaimCodeLookup_09] FOREIGN KEY ([RoofShapeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_PropertyLossEvent_ClaimCodeLookup_10] FOREIGN KEY ([RoofPitchId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_PropertyLossEvent_ClaimCodeLookup_11] FOREIGN KEY ([RoofInspectedId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_PropertyLossEvent_ClaimCodeLookup_12] FOREIGN KEY ([RoofFullReplacedId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_PropertyLossEvent_LossEvent_01] FOREIGN KEY ([LossEventId]) REFERENCES [dbo].[LossEvent] ([LossEventId]),
    CONSTRAINT [FK_PropertyLossEvent_Party_01] FOREIGN KEY ([EMSCoId]) REFERENCES [dbo].[Party] ([PartyId])
) ON [CLAIMSCD];

