CREATE TABLE [dbo].[Quote] (
    [QuoteNbr]                    VARCHAR (16)  NOT NULL,
    [LineofBusinessCd]            CHAR (2)      NOT NULL,
    [SublineBusinessTypeCd]       CHAR (1)      NOT NULL,
    [AgentNbr]                    CHAR (4)      NULL,
    [CompanyNbr]                  CHAR (3)      NULL,
    [PolicyMembershipNbr]         CHAR (10)     NULL,
    [TemporaryMembershipNbr]      CHAR (10)     NULL,
    [QuoteIssueDt]                DATE          NULL,
    [AccountBillNbr]              CHAR (10)     NULL,
    [ActivePropertyCd]            CHAR (1)      NULL,
    [BookletNbr]                  VARCHAR (10)  NULL,
    [BookletEditionDt]            DECIMAL (5)   NULL,
    [ExposureMonthsCd]            CHAR (2)      NULL,
    [OriginalInceptionDt]         DATE          NULL,
    [QuoteEffectiveDt]            DATE          NULL,
    [QuoteExpirationDt]           DATE          NULL,
    [SuppressCommissionInd]       CHAR (1)      NULL,
    [TermCd]                      CHAR (2)      NULL,
    [UnderwriterID]               CHAR (4)      NULL,
    [DiscountMembershipNbr]       CHAR (10)     NULL,
    [TransactionDt]               DATE          NULL,
    [NonPayCancellationCnt]       DECIMAL (3)   NULL,
    [UpdatedTmstmp]               DATETIME2 (7) NOT NULL,
    [LegacyDiscountMembershipNbr] CHAR (10)     NULL,
    [QuoteConvertedInd]           BIT           NULL,
    [PolicyNbr]                   VARCHAR (16)  NULL,
    [LatestQuoteInd]              BIT           NULL,
    [ProductCd]                   VARCHAR (64)  NULL,
    [BindInd]                     BIT           NULL,
    [UserUpdatedId]               CHAR (8)      NOT NULL,
    [BoundTmstmp]                 DATETIME      NULL,
    [NewBusinessProcessDt]        DATE          NULL,
    [LastActionCd]                CHAR (1)      NOT NULL,
    [ApplicationStatusDesc]       VARCHAR (100) NULL,
    [SourceSystemCd]              CHAR (2)      NOT NULL,
    [SourceSystemId]              INT           NOT NULL,
    CONSTRAINT [PK_Quote] PRIMARY KEY CLUSTERED ([QuoteNbr] ASC) ON [POLICYCD]
) ON [POLICYCD];

