CREATE TABLE [dbo].[Recovery] (
    [ClaimFinancialTransactionID] INT             CONSTRAINT [DF_RecoveryID] DEFAULT ((0)) NOT NULL,
    [ClaimRecoveryTypeId]         INT             NOT NULL,
    [ClaimRecoveryPaymentId]      INT             NULL,
    [RecoveryCategoryId]          INT             NOT NULL,
    [RecoveryPayorID]             INT             NULL,
    [SalvageRecoveryAmt]          DECIMAL (18, 2) NOT NULL,
    [SubrogationRecoveryAmt]      DECIMAL (18, 2) NOT NULL,
    [ExpenseRecoveryAmt]          DECIMAL (18, 2) NOT NULL,
    [LossRecoveryAmt]             DECIMAL (18, 2) NOT NULL,
    [RecoveryPaymentTxt]          VARCHAR (255)   NULL,
    [ClaimUserCreateTime]         DATETIME2 (7)   NOT NULL,
    [ClaimUserCreatedId]          CHAR (8)        NOT NULL,
    [ClaimUpdatedTmstmp]          DATETIME2 (7)   NOT NULL,
    [ClaimUserUpdatedId]          CHAR (8)        NOT NULL,
    [RetiredInd]                  CHAR (1)        NOT NULL,
    [SourceSystemId]              INT             NOT NULL,
    [EQRecoveryInd]               CHAR (1)        NULL,
    [UpdatedTmstmp]               DATETIME2 (7)   NOT NULL,
    [UserUpdatedId]               CHAR (8)        NOT NULL,
    [LastActionCd]                CHAR (1)        NOT NULL,
    [SourceSystemCd]              CHAR (2)        NOT NULL,
    CONSTRAINT [PK_Recovery] PRIMARY KEY CLUSTERED ([ClaimFinancialTransactionID] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_Recovery_ClaimCodeLookup_01] FOREIGN KEY ([RecoveryCategoryId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Recovery_ClaimCodeLookup_02] FOREIGN KEY ([ClaimRecoveryTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Recovery_ClaimCodeLookup_03] FOREIGN KEY ([ClaimRecoveryPaymentId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_Recovery_ClaimFinancialTransaction_01] FOREIGN KEY ([ClaimFinancialTransactionID]) REFERENCES [dbo].[ClaimFinancialTransaction] ([ClaimFinancialTransactionId]),
    CONSTRAINT [FK_Recovery_Party_01] FOREIGN KEY ([RecoveryPayorID]) REFERENCES [dbo].[Party] ([PartyId])
) ON [CLAIMSCD];

