CREATE TABLE [dbo].[ReinsuranceCategory] (
    [REINCategoryId]      INT            NOT NULL,
    [CompanyNbr]          CHAR (3)       NOT NULL,
    [LineCd]              VARCHAR (3)    NOT NULL,
    [CategoryCd]          CHAR (2)       NOT NULL,
    [CategoryEffectiveDt] DATE           NULL,
    [CategoryExpiryDt]    DATE           NULL,
    [MinimumLimitAmt]     DECIMAL (9)    NOT NULL,
    [MaximumLimitAmt]     DECIMAL (9)    NOT NULL,
    [CategoryPercent1Amt] DECIMAL (5, 4) NOT NULL,
    [CategoryPercent2Amt] DECIMAL (5, 4) NOT NULL,
    [CategoryPercent3Amt] DECIMAL (5, 4) NOT NULL,
    [PropertyPercentAmt]  DECIMAL (5, 4) NOT NULL,
    [AAICCategoryCd]      CHAR (2)       NOT NULL,
    [AAICLineCd]          CHAR (3)       NOT NULL,
    [ClaimUpdatedTmstmp]  DATETIME2 (7)  NOT NULL,
    [ClaimUserUpdatedId]  CHAR (8)       NOT NULL,
    [ClaimUserActionCd]   CHAR (1)       NOT NULL,
    [UpdatedTmstmp]       DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]       CHAR (8)       NOT NULL,
    [LastActionCd]        CHAR (1)       NOT NULL,
    [SourceSystemCd]      CHAR (2)       NOT NULL,
    CONSTRAINT [PK_ReinsuranceCategory] PRIMARY KEY CLUSTERED ([REINCategoryId] ASC) ON [CLAIMSCD]
) ON [CLAIMSCD];

