CREATE TABLE [dbo].[SubrogationAdverseParty] (
    [SubrogationAdversePartyId]       INT            NOT NULL,
    [AdversePartyId]                  INT            NOT NULL,
    [SubrogationClassificationId]     INT            NULL,
    [InsuranceInvolvedId]             INT            NULL,
    [MainContactTypeId]               INT            NULL,
    [ScheduleRecoveryTypeId]          INT            NULL,
    [SubrogationGovernmentInvolvedId] INT            NULL,
    [ExpectedRecoveryPct]             DECIMAL (5, 2) NULL,
    [FaultPct]                        DECIMAL (5, 2) NULL,
    [NoteReceivedDt]                  DATE           NULL,
    [NoteSentDt]                      DATE           NULL,
    [ScheduleRecoveryInd]             CHAR (1)       NULL,
    [CurrentRecordInd]                BIT            NOT NULL,
    [RetiredInd]                      CHAR (1)       NOT NULL,
    [SourceSystemId]                  INT            NOT NULL,
    [SourceSystemCreatedTmstmp]       DATETIME2 (7)  NOT NULL,
    [SourceSystemUserCreatedId]       CHAR (10)      NOT NULL,
    [SourceSystemUpdatedTmstmp]       DATETIME2 (7)  NOT NULL,
    [SourceSystemUserUpdatedId]       CHAR (10)      NOT NULL,
    [UpdatedTmstmp]                   DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]                   CHAR (8)       NOT NULL,
    [LastActionCd]                    CHAR (1)       NOT NULL,
    [SourceSystemCd]                  CHAR (2)       NOT NULL,
    CONSTRAINT [PK_SubrogationAdverseParty] PRIMARY KEY CLUSTERED ([SubrogationAdversePartyId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_SubrogationAdverseParty_ClaimCodeLookup_01] FOREIGN KEY ([MainContactTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_SubrogationAdverseParty_ClaimCodeLookup_02] FOREIGN KEY ([ScheduleRecoveryTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_SubrogationAdverseParty_ClaimCodeLookup_03] FOREIGN KEY ([SubrogationGovernmentInvolvedId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_SubrogationAdverseParty_ClaimCodeLookup_04] FOREIGN KEY ([InsuranceInvolvedId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_SubrogationAdverseParty_ClaimCodeLookup_05] FOREIGN KEY ([SubrogationClassificationId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_SubrogationAdverseParty_Party_01] FOREIGN KEY ([AdversePartyId]) REFERENCES [dbo].[Party] ([PartyId])
) ON [CLAIMSCD];

