CREATE TABLE [dbo].[SubrogationDetails] (
    [SubrogationDetailsId]                INT            NOT NULL,
    [SubrogationReferralCommentsId]       INT            NULL,
    [SubrogationReferralRationaleId]      INT            NULL,
    [SubrogationClosedOutcomeId]          INT            NULL,
    [EscalateSubrogationInd]              CHAR (1)       NULL,
    [ExternalOwnedInd]                    CHAR (1)       NULL,
    [ClaimConnectedInd]                   CHAR (1)       NULL,
    [InsuredAddressUpdatedInd]            CHAR (1)       NULL,
    [InsuredPhoneCompletedInd]            CHAR (1)       NULL,
    [PhotographsInd]                      CHAR (1)       NULL,
    [PoliceReportInd]                     CHAR (1)       NULL,
    [ResponsiblePartyAddressCompletedInd] CHAR (1)       NULL,
    [StatementsObtainedInd]               CHAR (1)       NULL,
    [SubrogationReserveOpenInd]           CHAR (1)       NULL,
    [UninsuredMotoristClaimSettledInd]    CHAR (1)       NULL,
    [AccidentFactsTxt]                    VARCHAR (2000) NULL,
    [SubrogationClosedCommentsTxt]        VARCHAR (255)  NULL,
    [SubrogationClosedDt]                 DATE           NULL,
    [SubrogationReferralCommentsTxt]      VARCHAR (255)  NULL,
    [SubrogationReferralDt]               DATE           NULL,
    [CurrentRecordInd]                    BIT            NOT NULL,
    [RetiredInd]                          CHAR (1)       NOT NULL,
    [SourceSystemId]                      INT            NOT NULL,
    [SourceSystemCreatedTmstmp]           DATETIME2 (7)  NOT NULL,
    [SourceSystemUserCreatedId]           CHAR (10)      NOT NULL,
    [SourceSystemUpdatedTmstmp]           DATETIME2 (7)  NOT NULL,
    [SourceSystemUserUpdatedId]           CHAR (10)      NOT NULL,
    [UpdatedTmstmp]                       DATETIME2 (7)  NOT NULL,
    [UserUpdatedId]                       CHAR (8)       NOT NULL,
    [LastActionCd]                        CHAR (1)       NOT NULL,
    [SourceSystemCd]                      CHAR (2)       NOT NULL,
    CONSTRAINT [PK_SubrogationDetails] PRIMARY KEY CLUSTERED ([SubrogationDetailsId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_SubrogationDetails_ClaimCodeLookup_01] FOREIGN KEY ([SubrogationReferralCommentsId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_SubrogationDetails_ClaimCodeLookup_03] FOREIGN KEY ([SubrogationClosedOutcomeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_SubrogationDetails_ClaimCodeLookup_04] FOREIGN KEY ([SubrogationReferralRationaleId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId])
) ON [CLAIMSCD];

