CREATE TABLE [dbo].[UmbrellaPolicy] (
    [PolicyId]                       INT           NOT NULL,
    [LineofBusinessCd]               CHAR (2)      NOT NULL,
    [SublineBusinessTypeCd]          CHAR (1)      NOT NULL,
    [PolicyNbr]                      VARCHAR (16)  NOT NULL,
    [PolicyTypeCd]                   CHAR (1)      NULL,
    [PartnershipPct]                 INT           NULL,
    [IRPMPct]                        INT           NULL,
    [ExposureAmt]                    INT           NULL,
    [ClassCd]                        CHAR (5)      NULL,
    [TerritoryCd]                    CHAR (1)      NULL,
    [CategoryCd]                     CHAR (1)      NULL,
    [ExposureBaseBrokerAmt]          INT           NULL,
    [ComputerRatedLevelCd]           CHAR (1)      NULL,
    [AAICFactorCd]                   CHAR (1)      NULL,
    [AcresNbr]                       INT           NULL,
    [AdditionalLegalEntitiesCnt]     INT           NULL,
    [Feet0To26SailBoatsCnt]          INT           NULL,
    [HeavyTrucksCnt]                 INT           NULL,
    [HP0To50WaterCraftsCnt]          INT           NULL,
    [HP51To200WaterCraftsCnt]        INT           NULL,
    [HP201To400WaterCraftsCnt]       INT           NULL,
    [Over400HPWaterCraftsCnt]        INT           NULL,
    [JetSkisCnt]                     INT           NULL,
    [MotorCyclesCnt]                 INT           NULL,
    [MotorHomesCnt]                  INT           NULL,
    [NonKFBVehiclesCnt]              INT           NULL,
    [NonStandardAutosCnt]            INT           NULL,
    [RentalUnitsCnt]                 INT           NULL,
    [Miles200RadiusTrailerTrucksCnt] INT           NULL,
    [Miles50RadiusTrailerTrucksCnt]  INT           NULL,
    [UnlicensedRVsCnt]               INT           NULL,
    [YouthfulDriversCnt]             INT           NULL,
    [TotalManWorkDaysCnt]            INT           NULL,
    [LightAndMediumTrucksCnt]        INT           NULL,
    [Over26FeetSailBoatsCnt]         INT           NULL,
    [AllActivePolicyInd]             CHAR (1)      NULL,
    [AutoExposureInd]                CHAR (1)      NULL,
    [BoatExposureInd]                CHAR (1)      NULL,
    [ClassRiskCd]                    VARCHAR (22)  NULL,
    [LegalEntityTypeDesc]            VARCHAR (50)  NULL,
    [LocationExposureInd]            CHAR (1)      NULL,
    [NoActivePolicyDesc]             VARCHAR (255) NULL,
    [OwnerOccupiedDwellingsCnt]      INT           NULL,
    [ReinsuranceCategoryCd]          CHAR (2)      NULL,
    [SurchargeExemptInd]             CHAR (1)      NULL,
    [PrivatePassengerAutomobilesCnt] INT           NULL,
    [NonKFBPolicyVehicleInd]         CHAR (1)      NULL,
    [PreferredRiskInd]               CHAR (1)      NULL,
    [PermitOwnerNm]                  VARCHAR (255) NULL,
    [RentedInd]                      CHAR (1)      NULL,
    [TerrorismCoverageInd]           CHAR (1)      NULL,
    [ICCPUCPSCInd]                   CHAR (1)      NULL,
    [OtherDetailsDesc]               VARCHAR (255) NULL,
    [UpdatedTmstmp]                  DATETIME2 (7) NOT NULL,
    [UserUpdatedId]                  CHAR (8)      NOT NULL,
    [LastActionCd]                   CHAR (1)      NOT NULL,
    [SourceSystemCd]                 CHAR (2)      NOT NULL,
    CONSTRAINT [PK_UmbrellaPolicy] PRIMARY KEY CLUSTERED ([PolicyId] ASC) ON [POLICYCD],
    CONSTRAINT [FK_UmbrellaPolicy_Policy_01] FOREIGN KEY ([PolicyId]) REFERENCES [dbo].[Policy] ([PolicyId])
) ON [POLICYCD];

