CREATE TABLE [dbo].[UmbrellaUnit] (
    [UnitNbr]                         INT           NOT NULL,
    [PolicyId]                        INT           NOT NULL,
    [PolicyNbr]                       VARCHAR (16)  NOT NULL,
    [ErrorsAndOmissionsAgentNbr]      CHAR (4)      NULL,
    [ManurePitsNbr]                   INT           NULL,
    [UndergroundTanksNbr]             INT           NULL,
    [TotalFarmSitesNbr]               INT           NULL,
    [PollutionReferenceCd]            CHAR (1)      NULL,
    [TotalVehiclesCnt]                INT           NULL,
    [UninsuredMotoristCoverageInd]    CHAR (1)      NULL,
    [UnderinsuredMotoristCoverageInd] CHAR (1)      NULL,
    [OfficesCnt]                      INT           NULL,
    [IncidentalBusinessPursuitsCnt]   INT           NULL,
    [TeachersLiabilityInd]            CHAR (1)      NULL,
    [AerialSprayingInd]               CHAR (1)      NULL,
    [KFBAgentOfficesCnt]              INT           NULL,
    [TotalAcresCnt]                   INT           NULL,
    [MiscellaneousDesc]               VARCHAR (300) NULL,
    [AAICFactorCd]                    CHAR (1)      NULL,
    [ActiveAllinesPolicyInd]          CHAR (1)      NULL,
    [VehicleExposureInd]              CHAR (1)      NULL,
    [BoatExposureInd]                 CHAR (1)      NULL,
    [ClassRiskCd]                     VARCHAR (22)  NULL,
    [LegalEntityTypeDesc]             VARCHAR (50)  NULL,
    [LocationExposureInd]             CHAR (1)      NULL,
    [NoActivePolicyDesc]              VARCHAR (255) NULL,
    [OwnerOccupiedDwellingCnt]        INT           NULL,
    [ReinsuranceCategoryCd]           CHAR (2)      NULL,
    [SurchargeExemptInd]              CHAR (1)      NULL,
    [TerritoryCd]                     CHAR (1)      NULL,
    [EffectiveDt]                     DATE          NULL,
    [ExpirationDt]                    DATE          NULL,
    [ExternalPolicyInd]               CHAR (1)      NULL,
    [InsuranceCompanyNm]              VARCHAR (80)  NULL,
    [PolicyTypeCd]                    CHAR (1)      NULL,
    [ExternalPolicyNbr]               VARCHAR (16)  NULL,
    [NonOwnedAutoCoverageInd]         CHAR (1)      NULL,
    [AllStatesLiabilityInd]           CHAR (1)      NULL,
    [JonesFELAAdmiraltyExposureInd]   CHAR (1)      NULL,
    [SourceSystemId]                  INT           NULL,
    [UpdatedTmstmp]                   DATETIME2 (7) NOT NULL,
    [UserUpdatedId]                   CHAR (8)      NOT NULL,
    [LastActionCd]                    CHAR (1)      NOT NULL,
    [SourceSystemCd]                  CHAR (2)      NOT NULL,
    CONSTRAINT [PK_UmbrellaUnit] PRIMARY KEY CLUSTERED ([PolicyId] ASC, [UnitNbr] ASC) ON [POLICYCD],
    CONSTRAINT [FK_UmbrellaUnit_UmbrellaPolicy_01] FOREIGN KEY ([PolicyId]) REFERENCES [dbo].[UmbrellaPolicy] ([PolicyId])
) ON [POLICYCD];


GO
CREATE NONCLUSTERED INDEX [IX_UmbrellaUnit_01]
    ON [dbo].[UmbrellaUnit]([PolicyId] ASC)
    ON [POLICYCI];

