CREATE TABLE [dbo].[UserClaimUserRole] (
    [UserClaimUserRoleId]         INT           NOT NULL,
    [ClaimUserRoleId]             INT           NOT NULL,
    [ClaimID]                     INT           NOT NULL,
    [LitigationId]                INT           NULL,
    [ExposureId]                  INT           NULL,
    [ClaimGroupId]                INT           NULL,
    [ClaimFinancialTransactionId] INT           NULL,
    [UserID]                      CHAR (8)      NOT NULL,
    [SourceSystemId]              INT           NOT NULL,
    [RetiredInd]                  CHAR (1)      NULL,
    [SourceSystemCd]              CHAR (2)      NOT NULL,
    [UpdatedTmstmp]               DATETIME2 (7) NOT NULL,
    [UserUpdatedId]               CHAR (8)      NOT NULL,
    [LastActionCd]                CHAR (1)      NOT NULL,
    [CurrentRecordInd]            BIT           NOT NULL,
    CONSTRAINT [PK_UserClaimUserRole] PRIMARY KEY CLUSTERED ([UserClaimUserRoleId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_Exposure_UserClaimUserRole_01] FOREIGN KEY ([ExposureId]) REFERENCES [dbo].[Exposure] ([ExposureId]),
    CONSTRAINT [FK_Litigation_UserClaimUserRole_01] FOREIGN KEY ([LitigationId]) REFERENCES [dbo].[Litigation] ([LitigationId]),
    CONSTRAINT [FK_UserClaimUserRole_Claim_01] FOREIGN KEY ([ClaimID]) REFERENCES [dbo].[Claim] ([ClaimID]),
    CONSTRAINT [FK_UserClaimUserRole_ClaimFinancialTransaction_01] FOREIGN KEY ([ClaimFinancialTransactionId]) REFERENCES [dbo].[ClaimFinancialTransaction] ([ClaimFinancialTransactionId]),
    CONSTRAINT [FK_UserClaimUserRole_ClaimGroup_01] FOREIGN KEY ([ClaimGroupId]) REFERENCES [dbo].[ClaimGroup] ([ClaimGroupId]),
    CONSTRAINT [FK_UserClaimUserRole_ClaimUserRole_01] FOREIGN KEY ([ClaimUserRoleId]) REFERENCES [dbo].[ClaimUserRole] ([ClaimUserRoleId])
) ON [CLAIMSCD];

