CREATE TABLE [dbo].[UserLocation] (
    [UserLocationId]      INT           NOT NULL,
    [UserMasterId]        INT           NOT NULL,
    [UserDetailId]        INT           NOT NULL,
    [UserID]              VARCHAR (20)  NOT NULL,
    [CompanyCd]           CHAR (2)      NULL,
    [AgencyNbr]           CHAR (3)      NULL,
    [ClaimBranchNbr]      CHAR (3)      NULL,
    [UserLocationNm]      VARCHAR (200) NULL,
    [AddressLine1Desc]    VARCHAR (100) NULL,
    [CityNm]              CHAR (30)     NULL,
    [StateOrProvinceCd]   CHAR (3)      NULL,
    [ZipCd]               VARCHAR (15)  NULL,
    [POBoxNbr]            INT           NULL,
    [LocationAddressDesc] VARCHAR (200) NULL,
    [CurrentRecordInd]    BIT           NOT NULL,
    [UpdatedTmstmp]       DATETIME2 (7) NOT NULL,
    [UserUpdatedId]       CHAR (8)      NOT NULL,
    [LastActionCd]        CHAR (1)      NOT NULL,
    [SourceSystemCd]      CHAR (2)      NOT NULL,
    CONSTRAINT [PK_UserLocation] PRIMARY KEY NONCLUSTERED ([UserLocationId] ASC),
    CONSTRAINT [FK_UserLocation_UserDetail_01] FOREIGN KEY ([UserDetailId]) REFERENCES [dbo].[UserDetail] ([UserDetailId]),
    CONSTRAINT [FK_UserLocation_UserMaster_01] FOREIGN KEY ([UserMasterId]) REFERENCES [dbo].[UserMaster] ([UserMasterId])
);

