CREATE TABLE [dbo].[VehicleLossEvent] (
    [LossEventId]                            INT            NOT NULL,
    [CollisionPointId]                       INT            NULL,
    [VehicleTypeId]                          INT            NULL,
    [DriverRelationToOwnerId]                INT            NULL,
    [DriverRelationId]                       INT            NULL,
    [LossPartyTypeID]                        INT            NULL,
    [RepairShopId]                           INT            NULL,
    [TowingAgencyId]                         INT            NULL,
    [AirbagsDeployedId]                      INT            NULL,
    [VehicleDrivableId]                      INT            NULL,
    [VehicleSubmergedId]                     INT            NULL,
    [VehicleLocationAddressId]               INT            NULL,
    [UnitNbr]                                INT            NULL,
    [InspectionRequiredInd]                  CHAR (1)       NULL,
    [AffidavitCompletedInd]                  CHAR (1)       NULL,
    [AirbagsDeployedInd]                     CHAR (1)       NULL,
    [AirbagsMissingInd]                      CHAR (1)       NULL,
    [CollisionInd]                           CHAR (1)       NULL,
    [AntiTheftInd]                           CHAR (1)       NULL,
    [SalvageAssignedDt]                      DATE           NULL,
    [VehicleRecoveredDt]                     DATE           NULL,
    [VehicleSoldDt]                          DATE           NULL,
    [EquipmentFailureInd]                    CHAR (1)       NULL,
    [FireBurnedEngineInd]                    CHAR (1)       NULL,
    [FireBurnedDashboradInd]                 CHAR (1)       NULL,
    [ExtricationInd]                         CHAR (1)       NULL,
    [FloodSaltWaterInd]                      CHAR (1)       NULL,
    [InteriorMissingInd]                     CHAR (1)       NULL,
    [CommercialTransportationNm]             VARCHAR (70)   NULL,
    [DriverDOBPopulatedByConversionDt]       DATE           NULL,
    [DriveSexPopulatedByConversionCd]        CHAR (1)       NULL,
    [DamageExceeds75PercentInd]              CHAR (1)       NULL,
    [LossOfUsePayInd]                        CHAR (1)       NULL,
    [LeaveAppraisalInd]                      CHAR (1)       NULL,
    [FireBurnWindshieldInd]                  CHAR (1)       NULL,
    [TotalLossInd]                           CHAR (1)       NULL,
    [MilesFromResidenceNbr]                  INT            NULL,
    [PaymentAuthorizeInd]                    CHAR (1)       NULL,
    [RentalCoverageInd]                      CHAR (1)       NULL,
    [TowingChargeDesc]                       VARCHAR (2000) NULL,
    [LocationDifferentFromInsuredAddressInd] CHAR (1)       NULL,
    [Mileage100KInd]                         CHAR (1)       NULL,
    [OdometerReadingNbr]                     INT            NULL,
    [OwnerRetainingSalvageInd]               CHAR (1)       NULL,
    [OwnerPermissionInd]                     CHAR (1)       NULL,
    [KYGovernmentInd]                        CHAR (1)       NULL,
    [MinorOnPolicyInd]                       CHAR (1)       NULL,
    [MajorComponentMissingInd]               CHAR (1)       NULL,
    [SalvageCompanyNm]                       VARCHAR (30)   NULL,
    [TotalLossPointsNbr]                     INT            NULL,
    [TrafficViolationCd]                     CHAR (1)       NULL,
    [VehicleLocationKnownInd]                CHAR (1)       NULL,
    [ClaimUserCreateTime]                    DATETIME2 (7)  NOT NULL,
    [ClaimUserCreatedId]                     CHAR (8)       NOT NULL,
    [ClaimUpdatedTmstmp]                     DATETIME2 (7)  NOT NULL,
    [ClaimUserUpdatedId]                     CHAR (8)       NOT NULL,
    [RetiredInd]                             CHAR (1)       NOT NULL,
    [SourceSystemId]                         INT            NOT NULL,
    [UserUpdatedId]                          CHAR (8)       NOT NULL,
    [UpdatedTmstmp]                          DATETIME2 (7)  NOT NULL,
    [LastActionCd]                           CHAR (1)       NOT NULL,
    [SourceSystemCd]                         CHAR (2)       NOT NULL,
    CONSTRAINT [PK_VehicleLossEvent] PRIMARY KEY CLUSTERED ([LossEventId] ASC) ON [CLAIMSCD],
    CONSTRAINT [FK_VehicleLossEvent_ClaimCodeLookup_01] FOREIGN KEY ([VehicleTypeId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_VehicleLossEvent_ClaimCodeLookup_02] FOREIGN KEY ([LossPartyTypeID]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_VehicleLossEvent_ClaimCodeLookup_03] FOREIGN KEY ([CollisionPointId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_VehicleLossEvent_ClaimCodeLookup_04] FOREIGN KEY ([DriverRelationToOwnerId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_VehicleLossEvent_ClaimCodeLookup_05] FOREIGN KEY ([DriverRelationId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_VehicleLossEvent_ClaimCodeLookup_06] FOREIGN KEY ([VehicleDrivableId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_VehicleLossEvent_ClaimCodeLookup_07] FOREIGN KEY ([AirbagsDeployedId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_VehicleLossEvent_ClaimCodeLookup_08] FOREIGN KEY ([VehicleSubmergedId]) REFERENCES [dbo].[ClaimCodeLookup] ([ClaimCodeLookupId]),
    CONSTRAINT [FK_VehicleLossEvent_LossEvent_01] FOREIGN KEY ([LossEventId]) REFERENCES [dbo].[LossEvent] ([LossEventId]),
    CONSTRAINT [FK_VehicleLossEvent_LossEventLocationAddress_01] FOREIGN KEY ([VehicleLocationAddressId]) REFERENCES [dbo].[LossEventLocationAddress] ([LossEventLocationAddressId]),
    CONSTRAINT [FK_VehicleLossEvent_Party_01] FOREIGN KEY ([RepairShopId]) REFERENCES [dbo].[Party] ([PartyId]),
    CONSTRAINT [FK_VehicleLossEvent_Party_02] FOREIGN KEY ([TowingAgencyId]) REFERENCES [dbo].[Party] ([PartyId])
) ON [CLAIMSCD];

